### ISSUE TITLE
FR: Code Examples

### ISSUE THREAD

**Issue by timendez** [firebase/firebase-admin-go#128]
Unfortunately the majority of the documentation linked to in the README does not have Golang examples. Trying to do something as simple as read data from a reference isn't very clear, especially for people new to Go.

It would be fantastic and super helpful if you could include some basic examples in this repo.

Thanks!

**Comment by hiranya911** [comment]
@timendez we maintain our documentation at https://firebase.google.com/docs, which has plenty of samples. For instance the database documentation can be found at https://firebase.google.com/docs/database/admin/start.

The links in the README file are just for the convenience of the developers working on the SDK. If you want quick access to some samples you can also check under https://github.com/firebase/firebase-admin-go/tree/master/snippets. These are the same examples that appear in our website.
