### ISSUE TITLE
Installing Firebase Error

### ISSUE THREAD

**Issue by CesarAlvarado** [firebase/firebase-admin-go#137]
**Environment**
OS: macOS High Sierra 10.13.4
go version go1.8.3 darwin/amd64

**Problem**
I have an error when installing the SDK when I run the command:

`go get firebase.google.com/go`

I get

```
# google.golang.org/grpc/transport
src/google.golang.org/grpc/transport/http_util.go:570: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)

```
When I build I get the exact same error as above.

`go test -test.short firebase.google.com/go/...`

I get

`# google.golang.org/grpc/transport
src/google.golang.org/grpc/transport/http_util.go:570: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
FAIL	firebase.google.com/go [build failed]
FAIL	firebase.google.com/go/auth [build failed]
FAIL	firebase.google.com/go/db [build failed]
FAIL	firebase.google.com/go/iid [build failed]
FAIL	firebase.google.com/go/integration/auth [build failed]
FAIL	firebase.google.com/go/integration/db [build failed]
FAIL	firebase.google.com/go/integration/firestore [build failed]
FAIL	firebase.google.com/go/integration/iid [build failed]`

**Comment by hiranya911** [comment]
`http2.SetReuseFramer()` is indeed defined: https://godoc.org/golang.org/x/net/http2#Framer.SetReuseFrames

Please update your dependencies. The SDK builds fine both locally and on Travis.
