### ISSUE TITLE
FR: Support getting multiple user records at once by email

### ISSUE THREAD

**Issue by CDDelta** [firebase/firebase-admin-go#138]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: -
  * Firebase SDK version: -
  * Library version: 2.7.0
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
Firebase auth admin SDK does not support getting multiple user records at once.

#### Steps to reproduce:
-

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by vr001** [comment]
Submitted a PR https://github.com/firebase/firebase-admin-go/pull/140. 

cc @CDDelta

**Comment by hiranya911** [comment]
@vr001 can you describe your exact use case a little bit? In what circumstances would you need this feature? Knowing this will allow us to convince the rest of the Firebase team that this is something worth pursuing.

Also, is the same required for finding users by uid and phone number?

**Comment by vr001** [comment]
My use case is almost similar to what CDDelta mentioned. @hiranya911

**Comment by hiranya911** [comment]
Auth team is doing some work to enable this feature. Stay tuned.

**Comment by CDDelta** [comment]
Hi @hiranya911, do you have any updates to share regarding this feature? Thanks!
