### ISSUE TITLE
FR: Add channel ID to AndroidConfig

### ISSUE THREAD

**Issue by ambernardino** [firebase/firebase-admin-go#139]
### Describe your environment
  * Messaging/Notifications

### Describe the problem

If you target Android 8.0 (API level 26) and post a notification without specifying a notification channel, the notification does not appear and the system logs an error.

If needed I can implement this feature.

**Comment by chemidy** [comment]
In the new [HTTP V1 API ](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification) android_channel_id is not present in the doc.

But in the [legacy Server Protocol](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) there was a android_channel_id.

Maybe an oversight ?

**Comment by hiranya911** [comment]
The FCM team is working on it.

**Comment by sampson-chen** [comment]
FCM team hopes to add this in the future for feature parity, but we do not have a timeline to share yet =)

**Comment by nadeemLGN** [comment]
Any updates on when this is going to be available on [HTTP V1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification)

**Comment by hiranya911** [comment]
This is now available in our REST APIs. Added to the SDK in #202
