### ISSUE TITLE
SDK v3.0.0 requires cloud.google.com/go v0.22.0.

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-go#147]
Firebase admin go SDK v3.0.0 requires cloud.google.com/go v0.22.0.

I saw this error because i have a constraint on cloud.google.com/go in my Gopkg.toml.

With v0.21.0 i have an error : 

```
# myproject/vendor/cloud.google.com/go/firestore
vendor/cloud.google.com/go/firestore/query.go:163:40: too few values in struct initializer
```

Maybe it's time to add a Gopkg.toml to ensure compatibility ?
Or add a note in the Readme ?

**Comment by hiranya911** [comment]
We generally build and test against the latest versions of our dependencies. It is nice to not have to worry about versioning dependencies. `cloud.google.com/go` does the same as far as I can tell. 

@chemidy can you elaborate on how the above error actually occurred? Your code has a dependency on Firestore 0.21.0, and Admin pulled in a more recent version. Is that what happened? 

If so can you drop the direct dependency on Firestore, and just declare a dependency on latest Admin SDK?

**Comment by hiranya911** [comment]
@CesarAlvarado we haven't changed anything in the Admin SDK end. It's the Cloud Firestore API that has changed. Since Firestore is currently in beta, they certainly can make API changes. You can checkout a specific Admin SDK [tag](https://github.com/firebase/firebase-admin-go/releases), but that's unlikely to solve this issue. You might want to checkout a specific version of Cloud Firestore from https://github.com/GoogleCloudPlatform/google-cloud-go/releases

**Comment by mauipipe** [comment]
@chemidy just used tried to install using both go get or dep, My app is not compiling anymore.

**Comment by chemidy** [comment]
With dep you can try this  in your Gopkg.toml : 

```yaml
[[override]]
  name = "cloud.google.com/go"
  branch = "master"
```

instead of 

```yaml
[[constraint]]
  name = "cloud.google.com/go"
  version = "v0.22.0"
```

**Comment by mauipipe** [comment]
@chemidy thank you this fixed the problem

**Comment by hiranya911** [comment]
@chemidy, others, is there anything that must be done in the SDK to resolve this?

**Comment by bejayoharen** [comment]
Is there a way to fix this with go get? (I assume this is the same issue, sorry if it's not):

    $ cd $GOPATH
    $ go get firebase.google.com/go
    package cloud.google.com/go/firestore: cannot find package "cloud.google.com/go/firestore" in any of:
    	/usr/local/Cellar/go/1.10.2/libexec/src/cloud.google.com/go/firestore (from $GOROOT).   
    	/Users/bjorn/Code/gocode/src/cloud.google.com/go/firestore (from $GOPATH)
    package cloud.google.com/go/storage: cannot find package "cloud.google.com/go/storage" in any of:
    	/usr/local/Cellar/go/1.10.2/libexec/src/cloud.google.com/go/storage (from $GOROOT)
    	/Users/bjorn/Code/gocode/src/cloud.google.com/go/storage (from $GOPATH)

**Comment by hiranya911** [comment]
@bejayoharen you probably need to pass the `-u` flag to the command.

**Comment by hiranya911** [comment]
I'm closing this since it doesn't look like that should be addressed in this repo.
