### ISSUE TITLE
Old GCM tokens result in The credential used to authenticate this SDK does not have permission .....

### ISSUE THREAD

**Issue by holoduke** [firebase/firebase-admin-go#148]
whenever I try to send a notification with an old GCM token I get:

{"code":"messaging/mismatched-credential","message":"The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token. Make sure the credential and registration token both belong to the same Firebase project."}}}

When I use a normal FCM token it works fine. So there is actually no authentication issue.

If it does not matter if i use admin.messaging().sendToDevice(.. or admin.messaging().subscribeToTopic(..  In both the same error. No error when FCM token is used.

For now i have no idea how to still support old GCM tokens.

**Comment by hiranya911** [comment]
First of `admin.messaging().sendToDevice()` looks like Node.js. Are you in the right place? Secondly, I don't think GCM tokens are supported in the new messaging API.

**Comment by hiranya911** [comment]
Closing since this seems to be at the wrong place.
