### ISSUE TITLE
FR: return identifiable errors in iid package

### ISSUE THREAD

**Issue by kaskavalci** [firebase/firebase-admin-go#149]
InstanceID client returns a formatted error message: https://github.com/firebase/firebase-admin-go/blob/master/iid/iid.go#L88

Caller cannot distinguish the error and take action. Errors should be public and returned error should be the error itself.

```go
if err, ok := errorCodes[resp.Status]; ok {
	return err
}
```

**Comment by hiranya911** [comment]
Fair enough. We need to expose error checking functions like we did in the `auth` package.

**Comment by hiranya911** [comment]
Fixed in #151
