### ISSUE TITLE
http.DefaultClient is not available in App Engine

### ISSUE THREAD

**Issue by fizzy123** [firebase/firebase-admin-go#162]
* Operating System version: Google App Engine
  * Firebase SDK version: 3.2.0
  * Firebase Product: Auth

http.DefaultClient is not available in App Engine

#### Steps to reproduce:

Import firebase into any application running in google app engine.

```
func init() {
  c := context.Background()
  app, err := firebase.NewApp(c, &firebase.Config{ProjectID: "example_id"})
  if err != nil {
    return nil, err
  }
  client, err := app.Auth(c)
  if err != nil {
    return nil, err
  }
  token := "example_token"
  _, err := a.client.VerifyIDToken(c, token)
}
```

#### Relevant Code:

```
	return &Client{	 	return &Client{
 		is:        is,
		keySource: newHTTPKeySource(idTokenCertURL, hc),	
 		projectID: conf.ProjectID,
 		signer:    signer,
 		version:   "Go/Admin/" + conf.Version,
 	}, nil
```
was changed to
```
	return &Client{	 	return &Client{
 		is:        is,
		keySource: newHTTPKeySource(idTokenCertURL, http.DefaultClient),
 		projectID: conf.ProjectID,
 		signer:    signer,
 		version:   "Go/Admin/" + conf.Version,
 	}, nil
```
https://github.com/firebase/firebase-admin-go/commit/1d2a52c3c8195451b5ad2e0a173906bd6eb9529d#diff-3ba8fa87da15d764efcb8ea0c83f6e97R132

**Comment by hiranya911** [comment]
Thanks @fizzy123 for pointing it out. Fix in progress.

**Comment by SebScoFr** [comment]
Any update on when this could get released? We also could do with the fix 🙂

**Comment by hiranya911** [comment]
I've been absolutely swamped. I'll find some time tomorrow (Friday) to get this released.

**Comment by SebScoFr** [comment]
Is there a way to make **go get** use the master branch for local development? Until this gets released.

**Comment by hiranya911** [comment]
This was released yesterday.
