### ISSUE TITLE
CredentialsFromJSON fails without specifying scopes

### ISSUE THREAD

**Issue by zeroflaw** [firebase/firebase-admin-go#166]
Setting up firestorm using the google.CredentialsFromJSON is a bit messy. The scopes are specified in a internals files (which I'm not allowed to import). So I've had to copy and pate this code into mine to get the login to work. 

[scopes](firebase-admin-go/internal/internal.go)
`// FirebaseScopes is the set of OAuth2 scopes used by the Admin SDK.
var FirebaseScopes = []string{
	"https://www.googleapis.com/auth/cloud-platform",
	"https://www.googleapis.com/auth/datastore",
	"https://www.googleapis.com/auth/devstorage.full_control",
	"https://www.googleapis.com/auth/firebase",
	"https://www.googleapis.com/auth/identitytoolkit",
	"https://www.googleapis.com/auth/userinfo.email",
}`

FYI, It works without specifying the scopes when loading from file, but I'm loading my json from an encrypted location, and I don't want to write the unencrypted value to disk. 

The following example works, 'j.ServiceAccount' contains json key file text, admit the scopes and it will fail to login.

```
cred, err := google.CredentialsFromJSON(ctx, j.ServiceAccount,
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/datastore",
		"https://www.googleapis.com/auth/devstorage.full_control",
		"https://www.googleapis.com/auth/firebase",
		"https://www.googleapis.com/auth/identitytoolkit",
		"https://www.googleapis.com/auth/userinfo.email")

	if err != nil {
	   //logging
	}

	sa := option.WithCredentials(cred)
	app, err := firebase.NewApp(ctx, nil, sa)
	if err != nil {
		 //logging
	}

	client, err := app.Firestore(ctx)
	if err != nil {
		 //logging
	}
	defer client.Close()

	_, _, err = client.Collection("users").Add(ctx, map[string]interface{}{
		"first": "Ada",
		"last":  "Lovelace",
		"born":  1815,
	})
	if err != nil {
	    //logging
	}
```

**Comment by hiranya911** [comment]
Don't specify any scopes. `firebase.NewApp()` adds all the required scopes by default:

https://github.com/firebase/firebase-admin-go/blob/1d2a52c3c8195451b5ad2e0a173906bd6eb9529d/firebase.go#L138-L140

**Comment by hiranya911** [comment]
Follow up at https://github.com/google/google-api-go-client/issues/284
