### ISSUE TITLE
FR: enable custom token creation on App Engine without a JSON credentials file

### ISSUE THREAD

**Issue by jprobinson** [firebase/firebase-admin-go#17]
In the App Engine standard environment, the code could likely be much simpler and easier to configure if it relied on [`appengine.ServiceAccount`](https://godoc.org/google.golang.org/appengine#ServiceAccount) and [`appengine.SignBytes`](https://godoc.org/google.golang.org/appengine#SignBytes) to generate custom auth tokens.

I imagine this would require a refactor to accept a `"context"` for most methods and also some additional finagling to prevent duplicate code across build tags, but it would definitely get me to lean on this library more.

An example of using the GAE tools to generate a custom token: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/appengine/firebase/tictactoe/firebase.go#L45-L69

I'm definitely interested in helping out by working on a PR if there's interest in this functionality.

**Comment by hiranya911** [comment]
Perhaps we can avoid the API change by using the context already present in `internal.AuthConfig`. I'm currently working towards making it possible to pass a context into `app.Auth()`, which will make that option more attractive. 

We can introduce a new private interface:
```
type signer interface {
  Email() string
  Sign(b []byte) (string, error)
}
```

Then provided we have a context already present in `auth.Client`, we can do something like the following in `CustomTokenWithClaims()`:
```
var s signer
var err error
if c.email != "" && c.pk != nil {
  s, err = newServiceAcctSigner(c.email, c.pk)
  if err != nil {
    return nil, err
  }
} else if isAppEngine() { // Not sure how to do this check
  s, err = newAppEngineSigner(c.ctx)
  if err != nil {
    return nil, err
  } 
} else {
  return nil, errors.New("service account parameters not available")
}
```

If you like feel free to put some code together, and I can take a look sometime next week.

**Comment by hiranya911** [comment]
This was [released](https://firebase.google.com/support/release-notes/admin/go#1.0.2) today. Thanks @jprobinson for contributing. Hope you would continue to support this project.

**Comment by ernsheong** [comment]
@hiranya911 would this be possible with Compute Engine, not App Engine?
