### ISSUE TITLE
How do you access the error code

### ISSUE THREAD

**Issue by davbeck** [firebase/firebase-admin-go#171]
I'm working at integrating Firebase messaging into our service. We are storing device tokens in our database and using that list to send notifications. For APNS (not using Firebase), we can get an api response that indicates the app has been uninstalled from the device and can remove the token from our database. I can see in the source code for this project that there is an error code for this (registrationTokenNotRegistered) but it is being returned in an error object that is in the internal package (FirebaseError) and returned as a generic error interface. Is there any way to access that Code property from the calling code? I'm new to Go so maybe I'm missing something obvious.

Thank you.

**Comment by hiranya911** [comment]
Use this: https://godoc.org/firebase.google.com/go/messaging#IsRegistrationTokenNotRegistered

**Comment by davbeck** [comment]
Perfect, thank you!
