### ISSUE TITLE
FR: Add subtitle for iOS push notifications

### ISSUE THREAD

**Issue by dobegor** [firebase/firebase-admin-go#173]
### Describe your environment
  * Messaging/Notifications

### Describe the problem
We cannot send push notifications with subtitle for iOS due to [ApsAlert](https://godoc.org/firebase.google.com/go/messaging#ApsAlert) struct lacking a `subtitle` field.

FCM API and the APNS itself do support this field on iOS 9+ (and it's safely ignored on older versions).

**Comment by hiranya911** [comment]
Will implement this eventually. Please provide a pull request if you want to speed things up.

**Comment by hiranya911** [comment]
This is implemented. Will be included in next release. Thanks @chmidy.
