### ISSUE TITLE
auth/Client.VerifyIDToken should verify (some) fields before checking signature

### ISSUE THREAD

**Issue by palsivertsen** [firebase/firebase-admin-go#174]
Field validation in auth/Client.VerifyIDToken(), like checking `Expires` and `IssuedAt`, should be done before the, potentially expensive, operation [verifyToken](https://github.com/firebase/firebase-admin-go/blob/10442ce72ae5afa134bdea11670094a04cfe5805/auth/auth.go#L223). Deep down `verifyToken` uses locking and issues a http request. Although this is not the biggest overhead, it would be nice if e.g. expired tokens where not dependent on sub-requests to Firebase API (an expired token is not valid no matter the signature)

**Comment by palsivertsen** [comment]
> Also note that the SDK caches HTTP calls to the public key server. So VerifyIDToken() only makes HTTP calls once every 24 hours or so.

Yes, I saw. But the locking still happens for every request

**Comment by hiranya911** [comment]
Fixed
