### ISSUE TITLE
Unable to set multiple client options

### ISSUE THREAD

**Issue by camstuart** [firebase/firebase-admin-go#177]
* Operating System version: OSX 10.13.6
  * Firebase SDK version: Unable to determine
  * Firebase Product:  Auth

Note: Running in GAE Standard dev environment under `dev_appserver.py`

I am attempting to verify firebase tokens, but I am not able to set up my `ClientOption` to use `urlfetch` by calling `WithHTTPClient`  when I am already using `WithCredentialsFile`

See example:
```golang
gaeCtx := appengine.NewContext(r)

opt := option.WithCredentialsFile("/path/to/my-app-service-account-file.json")
// opt := option.WithHTTPClient(urlfetch.Client(gaeCtx)) <--- How do I set this as well as WithCredentialsFile?

app, err := firebase.NewApp(goStdCtx.Background(), nil, opt)
if err != nil {
  log.Errorf(gaeCtx, "unable to initialise firebase application")
}

client, err := app.Auth(gaeCtx)
if err != nil {
  log.Errorf(gaeCtx, "unable to initialise firebase authentication client")
}

...

```

I am aware that when I deploy to GAE I will not need `WithCredentialsFile` but I want to be able to set both `WithCredentialsFile` and `WithHTTPClient` when running in development

**Comment by hiranya911** [comment]
`NewApp()` function accepts varargs. So you can do this:

```
opt1 := option.WithCredentialsFile("/path/to/my-app-service-account-file.json")
opt2 := option.WithHTTPClient(urlfetch.Client(gaeCtx))

app, err := firebase.NewApp(goStdCtx.Background(), nil, opt1, opt2)
if err != nil {
  log.Errorf(gaeCtx, "unable to initialise firebase application")
}
```
