### ISSUE TITLE
Question about FcmErrorCode

### ISSUE THREAD

**Issue by lufia** [firebase/firebase-admin-go#179]
### environment

  * Firebase SDK version: v3.4.0
  * Firebase Product: messaging

### question

I have looked FCM HTTP v1 API error response looks like:

```http
HTTP/2.0 404 Not Found
Content-Type: application/json; charset=UTF-8
Date: Fri, 28 Sep 2018 07:27:19 GMT

{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "UNREGISTERED"
      }
    ]
  }
}
```

Currently messaging/messaging.go is looked at `details` with expression: `d.Type == "type.googleapis.com/google.firebase.fcm.v1.FcmErrorCode"`.
Is `v1.FcmErrorCode` key correct?
https://github.com/firebase/firebase-admin-go/blob/master/messaging/messaging.go#L628

**Comment by hiranya911** [comment]
Good catch. I think it should be `FcmError`. 

@sampson-chen can you please confirm?

**Comment by sampson-chen** [comment]
Yes, it should be `FcmError`.

**Comment by hiranya911** [comment]
This has been fixed in the dev branch.
