### ISSUE TITLE
Issue when install package

### ISSUE THREAD

**Issue by tdh4vn** [firebase/firebase-admin-go#183]
Hi Firebase,
I using command go get firebase.google.com/go to install package, but it have some issue.

> src/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:114:28: undefined: proto.InternalMessageInfo

**Comment by xufwind95** [comment]
I'm having the same issue

**Comment by xufwind95** [comment]
i remove all the $GOPATH/src/ files, then install succeed

**Comment by hiranya911** [comment]
Caused by an out of date dependency. `go get -u` should resolve this.
