### ISSUE TITLE
FR: Manage Session Cookies

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-go#188]
Add Firebase Auth server-side session cookie management : https://firebase.google.com/docs/auth/admin/manage-cookies

**Comment by hiranya911** [comment]
This is blocked on https://github.com/googleapis/google-api-go-client/tree/master/identitytoolkit/v3 to get updated. @bojeil-google has there been any progress towards getting those API descriptions updated?

**Comment by wejick** [comment]
Need this feature too
Not sure if you can pick this up anytime soon, then can someone explain how to get the session cookie?
Looked onto node sdk it's using `identitytoolkit.googleapis.com` but can't find reference for `:createSessionCookie` API.

**Comment by fitzoh** [comment]
per @jadekler in googleapis/google-api-go-client#263 it's blocked until the firebase team updates the `identitytoolkit` API

**Comment by fproulx-eoscanada** [comment]
Will that be fixed soon . ?

**Comment by rcarver** [comment]
Any update here? I'd really like to use this feature.

**Comment by bojeil-google** [comment]
We apologize for the delay. We are still working on exposing these new APIs in our discovery doc.

**Comment by hiranya911** [comment]
This has been released.
