### ISSUE TITLE
Unable to set endpoint for messaging

### ISSUE THREAD

**Issue by djui** [firebase/firebase-admin-go#189]
I try to set the base url for the client library so that during testing I can run requests against a FCM mock instead of doing internet requests. However, even with the following code, I can see the attempts to reach the official base url:

```go
ctx := context.Background()
opts := []option.ClientOption{option.WithEndpoint("http://localhost:1234/")}
// opts = append(opts, option.WithoutAuthentication())
app, _ := firebase.NewApp(ctx, nil, opts...)
c, _ := firebaseApp.Messaging(ctx)

_, _ = c.Send(cox, nil)
```

```
POST /v1/projects/dummy-project-id/messages:send HTTP/1.1
Host: fcm.googleapis.com
User-Agent: Go-http-client/1.1
Content-Length: 71
Content-Type: application/json
Accept-Encoding: gzip
{"message":{"notification":{"title":"foo","body":"bar"},"token":"123"}}
```

```
HTTP/2.0 401 Unauthorized
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Nov 2018 18:37:10 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```

**Comment by hiranya911** [comment]
We currently ignore this option. It's simple enough to support -- it's just that nobody has asked for it before. We can look into supporting it in the future.

In the meantime I think you can implement your tests by using the `option.WithHTTPClient()` function, where the HTTP client is set up with a mock Transport/RoundTripper.

**Comment by djui** [comment]
Thanks, we thought about using the `option.WithHTTPClient()` but then decided to use for now use a thin client implementation for Messaging, internally. 

I will track this issue, and if you guys feel like it's worth implementing, will switch back. The clients are pretty compatible. I am just sorry to not provide a PR to address this myself due to time constraints.

**Comment by chemidy** [comment]
You can set the endpoint with ```c.fcmEndpoint```

```
ctx := context.Background()
app, _ := firebase.NewApp(ctx, nil, opts...)
c, _ := firebaseApp.Messaging(ctx)

// set endpoint here
c.fcmEndpoint = "http://localhost:1234/"

_, _ = c.Send(cox, nil)
```

**Comment by djui** [comment]
As `fcmEndpoint` is lowercased, thus unexported, I can’t access it.

**Comment by slirx** [comment]
> We currently ignore this option. It's simple enough to support -- it's just that nobody has asked for it before. We can look into supporting it in the future.
> 
> In the meantime I think you can implement your tests by using the `option.WithHTTPClient()` function, where the HTTP client is set up with a mock Transport/RoundTripper.

how can I do that with `option.WithHTTPClient()`? are there any examples?
