### ISSUE TITLE
FR: configure the sound for a critical alert

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-go#193]
### Describe your environment

  * IOS Messaging/Notifications

###  Describe the problem

We cannot send push notifications with support of critical alert Sound for iOS due to ApsAlert struct.

Use Sound struct to configure the sound for a critical alert [as described here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112)

**Comment by hiranya911** [comment]
It looks like `Aps` can have a `sound` specified as either a string or a dictionary. We can certainly facilitate that. Following up from how we support `alert` both as a string and an object:

```
type Aps struct {
   Sound string
   CriticalSouns *CriticalSound
   ...
}
```

Feel free to put a PR together.

In the meantime one should be able to do the following:

```
aps := &messaging.Aps{
  CustomData: map[string]interface{}{
    "sound": map[string]interface{}{
         // critical sound params
     },
  },
}
```

**Comment by hiranya911** [comment]
This has been implemented.
