### ISSUE TITLE
FR : add email action links

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-go#199]
Recently Implemented on node API : https://github.com/firebase/firebase-admin-node/pull/364

- [generateSignInWithEmailLink](https://github.com/googleapis/google-api-go-client/blob/master/identitytoolkit/v3/identitytoolkit-gen.go#L2751)

**Comment by hiranya911** [comment]
This is probably in the same boat as #188. @bojeil-google any update on when these REST API docs will be updated, so we can use the auto-generated Go client?

**Comment by bojeil-google** [comment]
Sorry about the delay. I will relay to the relevant parties.

**Comment by hiranya911** [comment]
We can implement this on top of REST directly (see #220) if anybody wants to take a stab at it.

**Comment by hiranya911** [comment]
This was implemented in #243 and #247
