### ISSUE TITLE
FR: `messaging.Aps` implements custom MarshalJSON but no UnmarshalJSON

### ISSUE THREAD

**Issue by omzouai-visor** [firebase/firebase-admin-go#207]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.14
  * Library version: v3.5.0
  * Firebase Product:messaging

### [REQUIRED] Step 3: Describe the problem

`messaging.Aps` implements a custom JSON marshaler, causing the Go JSON marshaler to use the custom implementation. Since the custom marshaler mutates the data, the resulting data cannot be unmarshaled back into the struct.

This prevents preparing APNS payloads and storing them in a database or queue for later dispatch.

#### Steps to reproduce:

1. Build an APNS Payload with a `ThreadID`
2. Call `json.Marshal(apnsPayload)`
3. Call `json.Unmarshal(apnsPayload, &target)`
4. See that fields such as `target.APNS.Payload.Aps.ThreadID` is empty.

#### Relevant Code:

```go
// MarshalJSON marshals an Aps into JSON (for internal use only).
func (a *Aps) MarshalJSON() ([]byte, error) {
	m := a.standardFields()
	for k, v := range a.CustomData {
		m[k] = v
	}
	return json.Marshal(m)
}
```

#### Solution:

Either make the custom JSON marshaler actually internal only by changing the names so that the Go JSON Marshaler cannot see the methods, or implement an unmarshaler

```go
// UnmarshalJSON unmarshals an Aps from JSON (for internal use only).
func (a *Aps) UnmarshalJSON(data []byte) error {
	m := make(map[string]interface{})
	a.CustomData = make(map[string]interface{})
	err := json.Unmarshal(data, &m)
	if err != nil {
		return err
	}
	for k, v := range m {
		switch k {
		case "alert":
			if v != nil {
				switch alert := m["alert"].(type) {
				case interface{}:
					a.Alert = alert.(*ApsAlert)
				case string:
					a.AlertString = alert
				}
			}
		case "content-available":
			if v == 1 {
				a.ContentAvailable = true
			}
		case "mutable-content":
			if v == 1 {
				a.MutableContent = true
			}
		case "badge":
			if v != nil {
				floatFromMap := m["badge"].(float64)
				intFromMap := int(floatFromMap)
				intPointer := &intFromMap
				a.Badge = intPointer
			}

		case "sound":
			if v != nil {
				a.Sound = m["sound"].(string)
			}

		case "category":
			if v != nil {
				a.Category = m["category"].(string)
			}

		case "thread-id":
			if v != nil {
				a.ThreadID = m["thread-id"].(string)
			}

		default:
			a.CustomData[k] = v
		}
	}
	return nil
}
```

**Comment by hiranya911** [comment]
This is fixed now
