### ISSUE TITLE
FR:  Token verification clock skew

### ISSUE THREAD

**Issue by fitzoh** [firebase/firebase-admin-go#210]
* Operating System version: Win 10
  * Firebase SDK version: ? 
  * Library version: v3.5.0
  * Firebase Product: auth

#### Steps to reproduce:

When I attempt to validate a token that was just created, it fails due to the token being created in the future.  This is presumably due to my clock being a couple milliseconds behind the firebase servers.

#### Relevant Code:
My server code
```
                tokenStr := "something just posted from the browser"
		token, err = authClient.VerifyIDToken(context.Background(), tokenStr)
		if err != nil{
			log.Printf("invalid token: %s", err)
		}
```
Firebase `auth.go` code
```
          else if payload.IssuedAt > clk.Now().Unix() {
		err = fmt.Errorf("ID token issued at future timestamp: %d", payload.IssuedAt)
	} 
```

The firebase code does a strict clock comparison with no tolerance for time skew.

I've been able to mitigate this by wrapping the call in a function with a backoff retry, but it would be nice if there was a first class method for managing clock skew.

```

func checkTokenWithSkewBackoff(tokenStr string) (*auth.Token, error) {
	var token *auth.Token
	var err error
	for _, d := range []time.Duration{0 * time.Millisecond, 10 * time.Millisecond, 100 * time.Millisecond, 1000 * time.Millisecond} {
		time.Sleep(d)
		token, err = authClient.VerifyIDToken(context.Background(), tokenStr)
		if err == nil || ! strings.HasPrefix(err.Error(), "ID token issued at future timestamp") {
			return token, err
		}
	}
	return token, err
}
```

**Comment by hiranya911** [comment]
In other languages we handle this by taking a fixed amount of clock skew (usually 5 minutes) into account. We can do the same here.

Here's the Python implementation for comparison:
https://github.com/googleapis/google-auth-library-python/blob/6e0781bb118a097b2398712901292d014a781278/google/auth/jwt.py#L176-L189

**Comment by hiranya911** [comment]
Fixed in the dev branch.
