### ISSUE TITLE
FR: User sign in with email link

### ISSUE THREAD

**Issue by gopalramadugu** [firebase/firebase-admin-go#212]
Is it possible to create a sign in method with email link only with Admin SDK ? I would like to use the same service in golang (Instead of having to maintain the web and mobile app services) for both my mobile app and website.

**Comment by hiranya911** [comment]
We haven't exposed any user authentication APIs in the Admin SDKs up to now. Nevertheless I'd like to run this by the Auth team and see what they think.

**Comment by bojeil-google** [comment]
We currently have no plans to expose authentication APIs in our Admin SDKs. Our authentication APIs were designed to run client side. You are welcome to file an official [feature request](https://firebase.google.com/support/) for that.

**Comment by bojeil-google** [comment]
Hey @oshalygin, we are quite unlikely to expose authentication APIs in our Admin SDKs. This would be a major change in how the system works and what the admin SDK is designed to do. You are always welcome to file an [official feature request](https://firebase.google.com/support/).
