### ISSUE TITLE
FR: Sending message to multi devices

### ISSUE THREAD

**Issue by canhlinh** [firebase/firebase-admin-go#213]
Hi team,

Do you have any plan to support sending message to multiple devices ?
As technical document was described at here https://firebase.google.com/docs/cloud-messaging/android/send-multiple

That would be nice if the `firebase-go` can support this feature.

**Comment by canhlinh** [comment]
@hiranya911 Sending message to multi tokens at the same time is a good choice.
I have already it with GCM and APNs. Please support on FCM

**Comment by chong-shao** [comment]
Hi @hiranya911, I think currently multicast is not supported by go SDK. Is there anything I can help?

**Comment by hiranya911** [comment]
I will eventually get to it. Developers are also invited to provide a pull request and help things move along.
