### ISSUE TITLE
Able to generate custom token even for a non existing uid

### ISSUE THREAD

**Issue by vr001** [firebase/firebase-admin-go#218]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: mac 10.13
  * Firebase SDK version: 3.4.0
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem
Initialized the firebase using service account set up with GOOGLE_APPLICATION_CREDENTIALS.
using authentication client with CustomToken(), I am able to generate a custom token even for the UID that doesn't exist in my project. Let me know if this is something expected behavior.

**Comment by bojeil-google** [comment]
This is the expected behavior. In fact this is the most common use case. Custom auth is used to sign in users for providers/sign in methods that Firebase Auth does not support.
If this is not desired for your project, you can always `getUser()` to check if the `uid` exists and if that returns no results, then fail the custom token generation request.

**Comment by vr001** [comment]
@bojeil-google Thanks for the quick response. So, the challenge is I am trying to verify the token which i generated using VerifyIDToken() and I am receiving invalid **JWT token failed to verify token signature**. Any help would be appreciated.

**Comment by hiranya911** [comment]
@vr001 how did you receive your ID token?

**Comment by hiranya911** [comment]
Ok, that makes sense. Although I'd expect the SDK to return a more specific error message in this case. Can you please comment on how you generated the custom token? I'd like to see if we can do something to improve the experience here.

**Comment by vr001** [comment]
Basically i created a custom token using CustomToken() and tried to verifying it using VerifyIDToken().

```
client, err := app.Auth(context.Background())
if err != nil {
        log.Fatalf("error getting Auth client: %v\n", err)
}

token, err := client.CustomToken(ctx, "some-uid")
if err != nil {
        log.Fatalf("error minting custom token: %v\n", err)
}

log.Printf("Got custom token: %v\n", token)
```

**Comment by hiranya911** [comment]
That's unusual. I get the error `expected an ID token but got a custom token` as expected when I run this:

```
func TestVerifyCustomToken(t *testing.T) {
       ct, err := client.CustomToken(context.Background(), uid)
	if err != nil {
		t.Fatal(err)
	}
	_, err = client.VerifyIDToken(context.Background(), ct)
	if err != nil {
		t.Fatal(err)
	}
}
```

https://github.com/firebase/firebase-admin-go/blob/f1dcecc6328cf3857fc970f450cca3965a90b422/auth/auth.go#L251-L257
