### ISSUE TITLE
Using HTTP Client for User Management

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-go#220]
In #60 we changed the user management code to use the auto-generated identity toolkit client instead of the HTTP client. This was a useful an interesting experiment that yielded some positive results in the short term. But I feel in the long run it has caused a couple of issues:

1. The auto-generated clients are not updated regularly, preventing us from launching new APIs at the pace we want.
2. We lose control over the transport layer, which makes it difficult to implement optimizations like retries in a single location.

Therefore, I'd like to consider going back to the HTTP client for user management. We can do this in steps:

1. Refactor the user mgt code and implement the currently missing APIs (e.g. session cookie management) on top of HTTP client without changing the existing APIs.
2. Incrementally migrate the existing user management APIs to also use the HTTP client.

@chemidy what do you think?

**Comment by chemidy** [comment]
I think this is a useful, we can deliver new functions very quickly 👍

**Comment by hiranya911** [comment]
We launched session cookie management API using this mechanism. I'll work on getting other APIs migrated as well.

**Comment by canhlinh** [comment]
@hiranya911 I've a question. Does firebase support GRPC for sending notifications ?

**Comment by hiranya911** [comment]
It probably does. @chong-shao should know more.

**Comment by chong-shao** [comment]
For v1 send API, currently it does not support gRPC.

**Comment by canhlinh** [comment]
@chong-shao Is there any API version are supporting gRPC ?

**Comment by chong-shao** [comment]
Hi @canhlinh, as far as I know there is no version that supports gRPC for now.

**Comment by canhlinh** [comment]
@chong-shao Thanks
