### ISSUE TITLE
FR: Created protoDocument from proto.Message preserves generated XXX_* fields.

### ISSUE THREAD

**Issue by hosaka** [firebase/firebase-admin-go#228]
Hello,

  * Operating System version: Ubuntu 18.04.2 LTS
  * Firebase SDK version: 3.6.0
  * Library version: _____
  * Firebase Product: (auth, storage)

#### Steps to reproduce:

I am looking for a quick protobuf to firestore push, without fiddling with json or string maps in go. Reading the code I saw that `data interface{}` can be a struct or a pointer to a struct, passing the pb.Message works perfectly fine, however it also serializes the generated XXX_ fields in my pb.go file. Please see the code for a quick example.

![Screenshot from 2019-03-11 20-00-49](https://user-images.githubusercontent.com/171876/54119338-6d0df780-4438-11e9-8f76-44de99d23db4.png)

Is this left as is on purpose or perhaps it's an oversight?
Thank you in advance!

#### Relevant Code:
```proto
message Note {
    int32 Id = 1;
    int32 GroupId = 2;
    int32 LocationId = 3;
    int32 OwnerId = 4;
}
```

```go
func (s *storeService) RegisterNote(ctx context.Context, in *Note) (*StoreResponse, error) {
	client, err := app.Firestore(ctx)

	_, _, err = client.Collection("notes").Add(ctx, in)

	return &StoreResponse{Success: true}, nil
}
```

**Comment by hiranya911** [comment]
Please report against the Firestore Go client: https://github.com/googleapis/google-cloud-go
