### ISSUE TITLE
Installing failure with go get

### ISSUE THREAD

**Issue by AndreiD** [firebase/firebase-admin-go#231]
By running 

**go get firebase.google.com/go**

I get:

~~~~
go: finding google.golang.org/api/option latest
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: golang.org/x/net@v0.0.0-20190125091013-d26f9f9a57f3: git fetch -f https://go.googlesource.com/net refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\workspace\pkg\m
od\cache\vcs\4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 1:
        error: Could not read 65e2d4e15006aab9813ff8769e768bbf4bb667a0
        fatal: bad object 65e2d4e15006aab9813ff8769e768bbf4bb667a0
        error: https://go.googlesource.com/net did not send all necessary objects
go: error loading module requirements
~~~~

  * Operating System version: go version go1.11.1 windows/amd64

  * Firebase SDK version: latest ?
  * Library version: latest ?
  * Firebase Product:

**Comment by AndreiD** [comment]
tried cloning the repo manually in GOPATH still no success

**Comment by AndreiD** [comment]
after deleting the go.sum contents, and running go get -d ./... it finally worked.
##  I see other people have also issues installing this library and I suggest you debug the problem.  You're freaking Google Devs, I thought they give you hard interview tests when they hire you... you should be able to fix this in no time.

**Comment by hiranya911** [comment]
As you can see the problem originated in a different repo:

```
go: golang.org/x/net@v0.0.0-20190125091013-d26f9f9a57f3: git fetch -f https://go.googlesource.com/net refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\workspace\pkg\m
od\cache\vcs\4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 1:
        error: Could not read 65e2d4e15006aab9813ff8769e768bbf4bb667a0
        fatal: bad object 65e2d4e15006aab9813ff8769e768bbf4bb667a0
        error: https://go.googlesource.com/net did not send all necessary objects
```

Most likely that repo was down or experiencing problems when you tried to install.  Nothing we can do about it in our codebase.

**Comment by AndreiD** [comment]
I see "googlesource.com" what should I do ? email devsupport@googlesource.com ? You work at google, you have access to their email... This is what's called "do more than what's written in your job description". Is it so hard to notify your colleagues that on their part something is not working.

**Comment by samtstern** [comment]
@AndreiD please try to be respectful on GitHub, we're all trying to do the right thing.  We've got a lot of SDKs and in order to maintain them we  have to draw a line between what we can actually fix, and what we can't.   We're certainly not saying that your problem is not real!  But the fix can't come from within this GitHub repo (or any that our team owns) so it's not productive to keep this issue as "open".

It sounds like the problem is somewhere in the golang toolchain.  I'd recommend sending a post to the mailing list below explaining your problem and I bet someone will have your solution:
https://groups.google.com/forum/#!forum/golang-nuts

**Comment by AndreiD** [comment]
this is not about me having my solution, it's about lots of other developer that have the same problem. You're not helping me to have "my solution". The problem is from YOUR ORGANIZATION, and all I'm asking is that you help your company provide better stuff. What you say is that you have too much to work and you don't care about 1 issue. So how many people must open the same issue for you to take action ? 5? 10? 100 ?  
I don't know what is https://go.googlesource.com/net 
do you ?
