### ISSUE TITLE
"go get firebase.google.com/go" error

### ISSUE THREAD

**Issue by renhuozhu** [firebase/firebase-admin-go#237]
hi,

when i  install  firebase admin go sdk.
the error occurs:

`go get firebase.google.com/go`

`package firebase.google.com/go: unrecognized import path "firebase.google.com/go" (https fetch: Get https://firebase.google.com/go?go-get=1: dial tcp 216.58.200.238:443: i/o timeout)`

can you help me to resolve this issue?

thanks  a lot!

**Comment by hiranya911** [comment]
Can you access the URL directly? https://firebase.google.com/go

If the problem occurs consistently, your machine might be behind a proxy or a firewall that's preventing connections to the above server. If not it was most likely a temporary issue (either on your end or on the server-end), and you can simply try again.

**Comment by renhuozhu** [comment]
it is the proxy problem.
i forget to set the proxy in the terminal .

thanks  for you help!
