### ISSUE TITLE
Misleading error message on 403 for messaging.Client().Send

### ISSUE THREAD

**Issue by ConradIrwin** [firebase/firebase-admin-go#238]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 10.14.3 
  * Firebase SDK version: 3.7.0
  * Library version: 3.7.0
  * Firebase Product: messaging

#### Steps to reproduce:

* Make a request to send a notification that fails with a 403 error.
* The error message will be "http error status: 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission", regardless of the cause of the error.
* Other ways you can trigger this:
* * Try to make a request with a service account with invalid permissions
* * Set the project-id wrong accidentally.

The "sender id does not match regisration" confused me for a while (it's also miss-spelt luckily so I was able to figure out that this was not a real error from the server). It turned out in my case to be that the service account I was using didn't have the right scopes.

#### Relevant Code:

```
app, _ := firebase.NewApp(ctx, nil)
m, _ := client.Messaging(ctx)
_, err := client.Send(ctx, message)
fmt.Println(err)
```

**Comment by hiranya911** [comment]
This is the error sent by the server in this case:

```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "..."
      }
    ]
  }
}
```

We map `PERMISSION_DENIED` to the above error message, but also include the error detail sent by the server (`The caller does not have permission`).

@chong-shao should we use a different error message for `PERMISSION_DENIED`? Note that this mapping has been adopted from the Node.js SDK, where we have been mapping `PERMISSION_DENIED` to `MISMATCHED_CREDENTIAL` for several years.

**Comment by chong-shao** [comment]
Hi @hiranya911, for this case can we forward the error details from the server without adding extra error messages in AdminSDK?

**Comment by hiranya911** [comment]
We currently add an error message for all errors using some shared code. 

https://github.com/firebase/firebase-admin-go/blob/c9b5e064033ed12864bf07d9bb34249087617130/messaging/messaging.go#L837-L847

Special casing an error code is going to require some work. This will get better/fixed once the new error handling proposal (go/firebase-error-handling) gets implemented. In the meantime, I think the easiest solution would be to update the common error message to something less ambiguous.

**Comment by hiranya911** [comment]
Fixed in the v4 branch along with the error handling major refactor.
