### ISSUE TITLE
go get firebase.google.com/go ( install Firebase Admin Go SDK failed)

### ISSUE THREAD

**Issue by Waterwolf-C4** [firebase/firebase-admin-go#24]
###: Describe the problem
try to setup firebase auth clinet and verify token on golang backend
follow https://firebase.google.com/docs/admin/setup

stop at #go get firebase.google.com/go

error message:
# firebase.google.com/go/auth
../firebase.google.com/go/auth/auth.go:82: c.Creds.JSON undefined (type *google.DefaultCredentials has no field or method JSON)
../firebase.google.com/go/auth/auth.go:87: c.Creds.JSON undefined (type *google.DefaultCredentials has no field or method JSON)

### : Describe of the environment

  * Operating System version: ubuntu 16.10
  * Firebase SDK version: 3.9.2
  * Firebase Product: auth

#### Steps to reproduce:

how to install this package 

#### Relevant Code:

```
import (
	"fmt"
	firebase "firebase.google.com/go"
	"golang.org/x/net/context"
	"google.golang.org/api/option"
)
	//Auth Backend with firebase
	// firebaseClient, err = FirebaseClient()
	opt := option.WithCredentialsFile("firebase-credentials.json")
	app, err := firebase.NewApp(context.Background(), nil, opt)
	if err != nil {
		fmt.Println("failed auth firebase client", err.Error())
		return
	}
	client, err := app.Auth()
	if err != nil {
		return err
	}
	decoded, err := client.VerifyIDToken("eyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY.XXXXXXXXXXXXXXXXXXXXXXX")
	if err != nil {
		fmt.Errorf("error verifying ID token: %v", err)
	}

	fmt.Printf("Verified ID token: %v\n", decoded)
```

**Comment by hiranya911** [comment]
You need to update your golang.org/x/oauth2 package. The `JSON` field was added to `DefaultCredentials` a few weeks ago:

https://godoc.org/golang.org/x/oauth2/google#DefaultCredentials
