### ISSUE TITLE
sender id does not match regisration token (not api or scope related)

### ISSUE THREAD

**Issue by derekperkins** [firebase/firebase-admin-go#248]
### [REQUIRED] Step 2: Describe your environment
  * Library version: 3.7.0
  * Firebase Product: messaging

Running on GKE

### [REQUIRED] Step 3: Describe the problem
Every call to send a message to cloud messaging returns this error:
`http error status 403; reason: sender id does not match regisration token; code: mismatched-credential; details: The caller does not have permission`

#### Related issues:
https://github.com/firebase/firebase-admin-go/issues/238 This was solved by adding scopes to the service account, but I have already added way more permissions to the account than it should require (listed below)
https://github.com/firebase/firebase-admin-go/issues/116 This was an issue with not enabling the Firebase Cloud Messaging API, but I have it enabled

#### Steps to reproduce:

Roles on my service account
```
Firebase Admin
Firebase Service Management Service Agent
Firebase Admin SDK Administrator Service Agent
Service Account Token Creator
```

I have checked quota usage here https://console.cloud.google.com/apis/api/fcm.googleapis.com/credentials and verified that the service account with the above permissions is the account being used to make the requests.

#### Relevant Code:

```
app, err := firebase.NewApp(c, nil)
fbClient, err := app.Messaging(c)
_, err := fbClient.Send(c, &messaging.Message{
	Data:  map[string]string{"some": "data"},
	Topic: "user_123",
})
```

**Comment by derekperkins** [comment]
cc @mordfustang21

**Comment by hiranya911** [comment]
How are you specifying the service account in the above code?

**Comment by derekperkins** [comment]
Using default credentials set up in the environment, the way we do with https://github.com/googleapis/google-cloud-go. That library is picking up credentials correctly for logging, tracing, pubsub, etc., and as I mentioned, it appears that this library is finding it too, since the quota is showing the specified service account as making all the attempts to send these messages.
`$GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/creds/application_default_credentials.json`

> Otherwise, NewApp attempts to authenticate the App with Google application default credentials.
https://godoc.org/firebase.google.com/go#NewApp

**Comment by hiranya911** [comment]
Can't really say anything specific based on the information provided here. I'd recommend you to file a support ticket, so we can take a look at your project specifically.

https://firebase.google.com/support

Once the issue has been submitted, you will be able to provide more project-specific details securely.

**Comment by derekperkins** [comment]
Done: Issue #3-2031000026493
Thanks!

**Comment by derekperkins** [comment]
So far Firebase support has been unhelpful.

> You should associate your service account xyz@myproject.iam.gserviceaccount.com as an 'owner' of your Firebase project to authorize your requests.

There is no role called "Firebase Owner", and I don't want to grant this service account "Owner" credentials to the entire GCP project. Their response was to make it at least an "Editor". I don't understand why I would need to grant "Editor" access to my entire project to a service account in order to send a Firebase Cloud Message? That's an old outdated way of doing IAM and I want to grant my service account the minimum privileges possible.

**Comment by hiranya911** [comment]
@chong-shao what are the permissions required to send FCM messages?

**Comment by chong-shao** [comment]
"sender id does not match registration token" means the registration token in the request is not registered under the google cloud project. If "sender id" is not a familiar concept to developers we should consider changing it to "project id" or "google project id" in the error message. If you are using HTTP in sending the request, the sender id can appear in your request URL: https://fcm.googleapis.com/v1/projects/[SENDER_ID]/messages:send 

The solution is to find the correct sender id (project id) associated with that token, and send with that sender id. Or to have the device register again with the correct project and send to the new registration token.

**[More information]** 
Regarding the other fixes discussed in this thread: 
1. Scope: I cannot think of any way scope can be related to this problem.
2. Service Account permission: there is a use case that: assume we have a cloud project "A". Project "A" has a service account "SA". SA can actually be added into another project "B"'s IAM list, and then you can generate oAuth tokens using SA's key and send to project B. So in some settings, changing the service account's permission may resolve this issue. But that depends on the actual config. The root cause should always be that the registration token is not registered with the project you are using.

**Comment by derekperkins** [comment]
Everything happening is in a single project. The service account is in the same GCP project as Firebase. Since the quota is showing usage on the service account, it seems to me that at least the GCP side is getting the right permissions. It's the Firebase configuration that I'm not familiar with.

**Comment by hiranya911** [comment]
@chong-shao the error message is probably incorrect in this instance (see #238). The client is receiving a 403 PERMISSION_DENIED for a request addressed to a topic. So no registration tokens are actually  involved (assuming the code sample given by the developer is indeed correct and up-to-date). That means it has to be a permissions issue, right? The service account is probably lacking some required permission?

**Comment by hiranya911** [comment]
@derekperkins Firebase projects are GCP projects. So that is not in issue here. But can you confirm that you're trying to send messages to a topic, and not a token?

**Comment by chong-shao** [comment]
Hi @derekperkins Have you tried to grant the "Editor" role to the service account? If an service account with Editor role works then we can confirm that it's a problem on our backend that returns the misleading error message.

**Comment by derekperkins** [comment]
Yes, I can confirm that I am sending to a topic. To clarify in case I am misunderstanding, the documentation says that the topic will be created on the fly, so I have not previous created this topic manually.
> When you use the API to subscribe a client app to a new topic (one that does not already exist for your Firebase project), a new topic of that name is created in FCM and any client can subsequently subscribe to it.

I created this service account via the GCP Console. I consider myself pretty familiar with IAM and we have specific role-scoped service accounts for all of our apps. This specific service account referenced here is being used in this same application via application default credentials for Stackdriver logging, tracing and monitoring, so I know it is mounted correctly.

I will try granting the "Editor" and retrying, but given the many roles I have already granted to it, I don't have a lot of faith that it will solve the problem.

**Comment by derekperkins** [comment]
I stand corrected, adding the "Editor" role allowed the message send to succeed, despite already having the following roles:

- Firebase Admin
- Firebase Service Management Service Agent
- Firebase Admin SDK Administrator Service Agent
- Service Account Token Creator
- a custom role with `firebaseanalytics.resources.googleAnalyticsReadAndAnalyze` `firebasenotifications.messages.create`

**Comment by derekperkins** [comment]
I'd like to figure out what the minimum permissions that need to be granted for this. My expectation is that it should only require `firebasenotifications.messages.create`, since I don't want this service account to list, get, delete or update.

I know the docs also reference all of these permissions, which seems excessive for just sending a message. I'd prefer to not include them in my role, but I will if I have to. They must not be sufficient however because they should be included in Firebase Admin and the other roles.

![image](https://user-images.githubusercontent.com/3588778/58736145-03a7e000-83ba-11e9-913c-3df16abd6669.png)

**Comment by chong-shao** [comment]
Hi @derekperkins , I think making a custom role by copying from "Firebase Grow Admin" role, and add permission "firebasenotifications.messages.create" should be sufficient. 

Please let me know if that works for you. We are working on adding "firebasenotifications.messages.create" into "Firebase Grow Admin" as one of the default permissions. 

On the other hand, I think AdminSDK or the backend has some issues in returning the correct error message for this case. We will try to reproduce the issue on our side and look into that.

**Comment by derekperkins** [comment]
I tried that and was unsuccessful. Here are all the permissions in my custom role that still don't allow me to send a message.
```
clientauthconfig.clients.get
clientauthconfig.clients.list
cloudconfig.configs.get
cloudconfig.configs.update
cloudnotifications.activities.list
firebase.billingPlans.get
firebase.clients.get
firebase.links.list
firebase.projects.get
firebaseabt.experimentresults.get
firebaseabt.experiments.create
firebaseabt.experiments.delete
firebaseabt.experiments.get
firebaseabt.experiments.list
firebaseabt.experiments.update
firebaseabt.projectmetadata.get
firebaseanalytics.resources.googleAnalyticsEdit
firebaseanalytics.resources.googleAnalyticsReadAndAnalyze
firebasedynamiclinks.destinations.list
firebasedynamiclinks.destinations.update
firebasedynamiclinks.domains.create
firebasedynamiclinks.domains.delete
firebasedynamiclinks.domains.get
firebasedynamiclinks.domains.list
firebasedynamiclinks.domains.update
firebasedynamiclinks.links.create
firebasedynamiclinks.links.get
firebasedynamiclinks.links.list
firebasedynamiclinks.links.update
firebasedynamiclinks.stats.get
firebaseextensions.configs.list
firebaseinappmessaging.campaigns.create
firebaseinappmessaging.campaigns.delete
firebaseinappmessaging.campaigns.get
firebaseinappmessaging.campaigns.list
firebaseinappmessaging.campaigns.update
firebasenotifications.messages.create
firebasenotifications.messages.delete
firebasenotifications.messages.get
firebasenotifications.messages.list
firebasenotifications.messages.update
firebasepredictions.predictions.create
firebasepredictions.predictions.delete
firebasepredictions.predictions.list
firebasepredictions.predictions.update
monitoring.timeSeries.list
resourcemanager.projects.get
resourcemanager.projects.getIamPolicy
servicemanagement.services.bind
servicemanagement.services.check
servicemanagement.services.create
servicemanagement.services.delete
servicemanagement.services.get
servicemanagement.services.getIamPolicy
servicemanagement.services.list
servicemanagement.services.quota
servicemanagement.services.report
servicemanagement.services.setIamPolicy
servicemanagement.services.update
serviceusage.operations.get
serviceusage.operations.list
serviceusage.quotas.get
serviceusage.services.get
serviceusage.services.list
```

**Comment by derekperkins** [comment]
I have now added all these roles to the service account and it still fails until I add the `Editor` role back.

```
Cloud Messaging Creator (Custom Role with the 64 permissions listed in the previous comment)
Firebase Admin
Firebase Analytics Admin
Firebase Develop Admin
Firebase Grow Admin
Firebase Quality Admin
Firebase Admin SDK Administrator Service Agent
Firebase Crash Symbol Uploader
Firebase Rules System
Service Account User
Viewer
```

**Comment by chong-shao** [comment]
@derekperkins sorry my mistake, could you repeat the steps described in my last comment, but add the permission "cloudmessaging.messages.create" instead of "firebasenotifications.messages.create" into your custom role?

**Comment by derekperkins** [comment]
@chong-shao you nailed it, all I needed was `cloudmessaging.messages.create` and no other permissions. My role currently works and only has the single permission, without any of the "required" permissions. Thanks for helping me get this working.

**Comment by kiithwarrior** [comment]
This solved my issue as well, thanks for posting.
