### ISSUE TITLE
repo: support go modules

### ISSUE THREAD

**Issue by kardianos** [firebase/firebase-admin-go#253]
This repo tags versions correctly for Go modules v3.x.y. However, the import paths it uses are incompatible with Go modules that use these tags.

I suspect you will need a go.mod file in the repository root with a module name with a trailing `v3`. Then import paths need to be adjusted to include the v3 as part of the import path.

**Comment by hiranya911** [comment]
Go mod support doesn't require any changes in existing libraries. It has been designed that way to enable easy migration. I use this SDK with Go mods all the time. Here are some examples:

https://github.com/hiranya911/firecloud/tree/master/api-management/clients
https://github.com/hiranya911/firecloud/tree/master/firedb-cli
https://github.com/hiranya911/firecloud/tree/master/review-scorer/scorer

**Comment by kardianos** [comment]
Okay, I support that's one response...

Thanks.
