### ISSUE TITLE
FR: export auth.tokenVerifier

### ISSUE THREAD

**Issue by nvcnvn** [firebase/firebase-admin-go#254]
https://github.com/firebase/firebase-admin-go/blob/be821cdc340e4dcaf1abf04910f727c8b8bda086/auth/token_verifier.go#L51

Export the `tokenVerifier` would be helpful for the use case when we just want to verify the token.

Another use case is user can override the `idTokenCertURL` or `sessionCookieCertURL` for testing
https://github.com/firebase/firebase-admin-go/blob/be821cdc340e4dcaf1abf04910f727c8b8bda086/auth/token_verifier.go#L42

**Comment by hiranya911** [comment]
We have no plans to add these types to the public API. In general we want to keep the internal implementation hidden, so we have control over it to make changes at will.

As for testing, you should define your own interfaces for these APIs so they can be mocked out easily:

```
interface TokenVerifier {
  VerifyIDToken(ctx context.Context, idToken string) (*auth.Token, error)
}
```

The `auth.Client` implicitly implements the above interface. You can specify your own custom implementation for unit testing.
