### ISSUE TITLE
Rename WebpushFcmOptions to WebpushFCMOptions

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-go#260]
We should do this rename in order to be consistent with Go conventions. This is unfortunately a breaking change, and therefore cannot be implemented until we plan a major release.

**Comment by chemidy** [comment]
Yes this is a breaking change, But i think the option currently not working because the param name is  fcmOptions instead of fcm_options (this is fixed in #256  )

**Comment by hiranya911** [comment]
Backend API accepts both `fcmOptions` and `fcm_options`. This was confirmed with the FCM team a while ago.

**Comment by hiranya911** [comment]
Fixed in the v4 branch
