### ISSUE TITLE
FR: Need PhoneVerified field in UserRecord

### ISSUE THREAD

**Issue by samuelg123** [firebase/firebase-admin-go#267]
* Operating System version: Windows 10 Pro - 1803
 * Library version: 3.9.0
 * Firebase Product: Auth

Hi,
I'm new to firebase auth. Is there any function to verify phone from firebase-admin-go (to check if it already verified in the client or not)? 

Thank you.

**Comment by hiranya911** [comment]
There's no such functionality built into Firebase Auth as far as I know.

**Comment by bojeil-google** [comment]
I assume you mean you want to differentiate that a phone number set via admin sdk is verified by the user client side. We haven't received much requests for this but I see its usefulness. Feel free to file a [feature request](https://firebase.google.com/support/) for it.

**Comment by samuelg123** [comment]
Oh okay sir. I just realize that my problem is in the client (flutter). When I call phone verification (from client), it will only register the phone to firebase once the verification is completed. So I didn't need to check phone (whether is verified or not) in firebase-admin-go. 
My problem solved. Thank you for the response 👍
