### ISSUE TITLE
Thrift is unreachable 

### ISSUE THREAD

**Issue by timotew** [firebase/firebase-admin-go#270]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 3: Describe the problem
`https://git.apache.org/thrift.git/` is currently down, If your project is not building see https://github.com/census-instrumentation/opencensus-go/issues/1158
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Use https://github.com/jenkins-x/jx/pull/3321/files for a workaround.

@hiranya911 should I make a PR to replace this dependency location?
#### Relevant Code:

```
[0m[91mgo: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0
[0m[91mgo: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
```

**Comment by hiranya911** [comment]
I don't think this can be fixed in this repo. We don't have a direct dependency on OpenCensus or Thrift. But if you know of a fix, feel free to provide a PR.

**Comment by timotew** [comment]
From the dependency map it appears, it's firestore that depends on this. I will reach out to them.
`
firebase.google.com/go ->
cloud.google.com/go/firestore->
cloud.google.com/go/firestore.test->
cloud.google.com/go/internal/testutil->
go.opencensus.io/trace->
go.opencensus.io/internal->
go.opencensus.io
`
