### ISSUE TITLE
FR: Verify ID tokens without requiring credentials

### ISSUE THREAD

**Issue by mykter** [firebase/firebase-admin-go#279]
* Firebase SDK version: 3.9.0
  * Firebase Product: auth

### Describe the problem
The firebase admin SDK is the most trustworthy way to verify ID tokens, but it isn't the easiest, because per the docs:

> To verify ID tokens with the Firebase Admin SDK, you must have a service account. Follow the Admin SDK setup instructions for more information on how to initialize the Admin SDK with a service account.

Technically, there's no need for this - to verify a token you just need to get certificates from a public endpoint.

It would be really helpful if `client.VerifyIDToken` function was also exposed as `auth.VerifyIDToken` so it could be used without having to initialize an app instance.

#### Steps to reproduce:
1. Try and verify ID tokens from a development machine, in CI, and in production.
2. Find you have to provision GCP credentials to do so
3. Increase risk by either writing your own verifier, using a third party solution (e.g. [1],[2],[3],[4],[5],[6],[7],[8] ...), or provisioning credentials where they aren't needed 

I think the number of public re-implementations of this logic in Go suggests there is demand for it.

[1]: https://github.com/LewisWatson/firebase-jwt-auth
[2]: https://github.com/alternaDev/go-firebase-verify
[3]: https://github.com/karlmoad/authentication
[4]: https://github.com/koichirokamoto/gko/blob/master/cloud/firebase/auth.go
[5]: https://github.com/khirayama/firebase-auth/blob/master/api-go/src/app/authHandler.go
[6]: https://github.com/dbubel/barrenschat-api/blob/master/middleware/auth.go
[7]: https://github.com/merlinapp/ms-authorization-go
[8]: https://github.com/guillaumeLeRoy/eritis_be/blob/master/firebase/token_verifier.go

**Comment by hiranya911** [comment]
You just need a project ID to verify ID tokens. You don't need a service account -- that part of the docs is incorrect. That means on environments that support ADC you can just do this:

```
config := &firebase.Config{
    ProjectID: "my-project-id",
}
app, err := firebase.NewApp(ctx, config)

client, err := app.Auth(ctx)
```

For environments without ADC, you can use the following trick:

```
config := &firebase.Config{
    ProjectID: "my-project-id",
}
ts := oauth2.StaticTokenSource(&oauth2.Token{})
app, err := firebase.NewApp(ctx, config, option.WithTokenSource(ts))

client, err := app.Auth(ctx)
```

**Comment by mykter** [comment]
Thanks! Might be worth capturing that in the docs?

**Comment by hiranya911** [comment]
@mykter I've filed an internal doc update request. Hopefully that page will get updated with more information.
