### ISSUE TITLE
FR: add IsInvalidEmail or publicize internal.FirebaseError

### ISSUE THREAD

**Issue by shogo82148** [firebase/firebase-admin-go#295]
### My environment

  * Operating System version: macOS Catalina 10.15.1
  * Firebase SDK version: v3.9.0
  * Library version: v3.9.0
  * Firebase Product: auth

### The problem

If I add a new user with malformed email address (e.g. `foo..bar@example.com`, `..` is not allowed by RFC) to Firebase Authentication, I get `INVALID_EMAIL` error.
I want to handle this error, but `IsInvalidEmail` is not in the [auth package](https://godoc.org/firebase.google.com/go/auth) and there is no way to get the error code.

```go
package main

import (
	"context"
	"log"

	firebase "firebase.google.com/go"
	"firebase.google.com/go/auth"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()
	opt := option.WithCredentialsFile("serviceAccountKey.json")
	app, err := firebase.NewApp(ctx, nil, opt)
	if err != nil {
		panic(err)
	}
	authClient, err := app.Auth(ctx)
	if err != nil {
		panic(err)
	}

	param := &auth.UserToCreate{}
	param.Email("foo..bar@example.com") // malformed email address `..` is not allowed.
	_, err = authClient.CreateUser(ctx, param)
	log.Println(err)
	log.Printf("%#v", err)

	// I want to handle INVALID_EMAIL error here.
}
```

```
2019/11/05 14:39:20 http error status: 400; body: {
  "error": {
    "code": 400,
    "message": "INVALID_EMAIL",
    "errors": [
      {
        "message": "INVALID_EMAIL",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

2019/11/05 14:39:20 &internal.FirebaseError{Code:"unknown-error", String:"http error status: 400; body: {\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"INVALID_EMAIL\",\n    \"errors\": [\n      {\n        \"message\": \"INVALID_EMAIL\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ]\n  }\n}\n"}
```

I want Firebase Admin SDK to add `IsInvalidEmail` function or publicize `internal.FirebaseError`.
How do you think about it?

**Comment by hiranya911** [comment]
I wonder if we should do a stronger validation in the SDK, and avoid making an RPC altogether if the email is invalid. This is what we do right now:

https://github.com/firebase/firebase-admin-go/blob/25e7c8260393cb8530bf311d2164f9a4875d2bc5/auth/user_mgt.go#L436-L444

If it is too complicated to check for this, adding an `IsInvalidEmail()` function sounds good to me.
