### ISSUE TITLE
Messaging issue (auth part)

### ISSUE THREAD

**Issue by Emixam23** [firebase/firebase-admin-go#301]
* Operating System version: Mac OS X
  * Firebase SDK version: Latest (Go module)
  * Firebase Product: Messaging

#### Steps to reproduce:

I have an issue I cannot import one package (internal one)

#### Relevant Code:

```
package fcm_test

import (
	firebase "firebase.google.com/go"
	"firebase.google.com/go/internal"
	"firebase.google.com/go/messaging"
	"fmt"
	"golang.org/x/net/context"
	"log"
)

func Test(message string, registrationToken string, topic string) {

	client, err := messaging.NewClient(context.Background(), &internal.MessagingConfig{})
	if err != nil {
		log.Fatal(err)
	}

	_, err = client.Send(context.Background(), &messaging.Message{
		Data:         map[string]string{"name": "data_test", "message": message},
		Notification: &messaging.Notification{
			Title:    "Title",
			Body:     "Body",
			ImageURL: "",
		},
		Android:      nil,
		Webpush:      nil,
		APNS:         nil,
		FCMOptions:   nil,
		Token:        registrationToken,
		Topic:        topic,
		Condition:    "",
	})
	if err != nil {
		log.Fatal(err)
	}

}
```

**Comment by hiranya911** [comment]
`internal` packages are only used for SDK's internal interactions. Users should not use it. Furthermore, the Go compiler will not allow external code to import any `internal` package: https://golang.org/s/go14internal

Users should access `messaging.Client` via `firebase.App`. Please see the documentation: https://firebase.google.com/docs/cloud-messaging/send-message

**Comment by Emixam23** [comment]
Alright thanks for your answer, I will dig into the link you gave me :)

**Comment by Emixam23** [comment]
From your link, I am keeping trying to use the SDK but I still have auth issue. I am unable to create my app:

```app, err := firebase.NewApp(context.Background(), nil)```

> google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

I looked a lot over the internet, I tried gcloud auth, the json file as exported env var, nothing work, I am still stuck

**Comment by hiranya911** [comment]
Try carefully going through the steps in https://firebase.google.com/docs/admin/setup. If you continue to see the above error, it's an indication that either the variable is not set, or it points to the wrong thing.

**Comment by Emixam23** [comment]
But I did try many approach and even now, I think I have the right one but I still have auth issue..

```
func Subscribe(registrationTokens []string, topic string) {

	credentialBytes, err := ioutil.ReadFile("credentials/creds.json")
	if err != nil {
		log.Fatalf("Unable to read client secret file: %v", err)
	}

	conf, err := google.JWTConfigFromJSON(credentialBytes, "https://www.googleapis.com/auth/firebase")
	opt := option.WithTokenSource(conf.TokenSource(context.Background()))

	// Generating the new app.
	app, err := firebase.NewApp(context.Background(), &firebase.Config{ProjectID: "my-awesome-project"}, opt)
	if err != nil {
		log.Fatal(err)
	}

	// Generating the new client from the app.
	client, err := app.Messaging(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	// These registration tokens come from the client FCM SDKs.
	// Subscribe the devices corresponding to the registration tokens to the
	// topic.
	response, err := client.SubscribeToTopic(context.Background(), registrationTokens, topic)
	if err != nil {
		log.Fatalln(err)
	}
	// See the TopicManagementResponse reference documentation
	// for the contents of response.
	fmt.Println(response.SuccessCount, "tokens were subscribed successfully")

}
```

From this I get 

```
err = {
    Code: "unknown-error"
    String: "http error status: 401; reason: client encountered an unknown error; response: <HTML><HEAD><TITLE>Unauthorized</TITLE></HEAD><BODY BGCOLOR="#FFFFFF" TEXT="#000000"><H1>Unauthorized</H1><H2>Error 401</H2></BODY></HTML>"
}
```

**Comment by hiranya911** [comment]
There are multiple places where you could have made an error:

1. Is the creds.json file a valid service account downloaded from the Firebase console?
2. You're explicitly specifying a scope in the `JWTConfigFromJSON`. I don't think specifying the Firebase scope is enough. You probably need the cloud-platform scope.
3. Does your project ID match the service account config?

I'm not sure why you're trying to authenticate the SDK this way. Generally all you have to do is:

```
export GOOGLE_APPLICATION_CREDENTIALS = path/to/validServiceAccount.json
```

Followed by:
```
app, err := firebase.NewApp(ctx, nil)
```
