### ISSUE TITLE
Bug : unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration

### ISSUE THREAD

**Issue by abdulrehmank** [firebase/firebase-admin-go#302]
* Operating System version: Ubuntu/MacOS
  * Firebase SDK version: v.3.10.0
  * Firebase Product: auth

#### Steps to reproduce:
Get the latest update and you will find that cloud.google.com/go have been updated. 

Error:
#### root/vendor/cloud.google.com/go/storage
vendor/cloud.google.com/go/storage/bucket.go:558:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:727:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:735:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:1077:18: b.UniformBucketLevelAccess undefined (type *storage.BucketIamConfiguration has no field or method UniformBucketLevelAccess)
vendor/cloud.google.com/go/storage/bucket.go:1080:39: b.UniformBucketLevelAccess undefined (type *storage.BucketIamConfiguration has no field or method UniformBucketLevelAccess)

The issue occurs after the recent update from cloud.google.com/go when it moved from 0.47.0 to 0.48.0.

**Comment by hiranya911** [comment]
cloud.google.com/go packages are developed at https://github.com/googleapis/google-cloud-go. Please report there.
