### ISSUE TITLE
go.mod in dev branch not following Semantic Import Versioning

### ISSUE THREAD

**Issue by ebati** [firebase/firebase-admin-go#307]
The current form of go.mod file in dev branch does not follow the rules suggested in [documentation](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). Related part is as follows:

> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg"). This includes the paths used in go get commands (e.g., go get github.com/my/mod/v2@v2.0.1. Note there is both a /v2 and a @v2.0.1 in that example. One way to think about it is that the module name now includes the /v2, so include /v2 whenever you are using the module name).

The module path should be changed to `firebase.google.com/go/v4` and released as a new major version. For alternatives and details you can check [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

**Comment by hiranya911** [comment]
@lahirumaramba something to watch out for when doing the next release.

**Comment by hiranya911** [comment]
Here's what I would propose:

1. Revert #293 which will remove the mod files.
2. Continue to release the Go SDK without explicit module support for a bit longer.
3. Release v4 of the SDK with module support (follow the guidelines at https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)

**Comment by hiranya911** [comment]
I will close this now. We have proper module support implemented in the `v4` branch. Will be released with the next major release.
