### ISSUE TITLE
Missing notification_priority  in Go SDK

### ISSUE THREAD

**Issue by max202021** [firebase/firebase-admin-go#308]
**Environment Details**
  * Operating System version: WIndows 10 
  * Firebase SDK version: 3.10.0
  * Firebase Product: Firebase Cloud Messaging

As Per firebase document, we can set the parameter **notification_priority** to determine message priority.

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

  ```
  {
      "title": string,
      "body": string,
      "icon": string,
      "color": string,
      "sound": string,
      "tag": string,
      "click_action": string,
      "body_loc_key": string,
      "body_loc_args": [
        string
      ],
      "title_loc_key": string,
      "title_loc_args": [
        string
      ],
      "channel_id": string,
      "ticker": string,
      "sticky": boolean,
      "event_time": string,
      "local_only": boolean,
      "notification_priority": enum (NotificationPriority),

```
I am trying to use firebase admin go client but when I see the message struct, I cannot see that element 

Struct Defined is as follows:
https://godoc.org/firebase.google.com/go/messaging#AndroidNotification

   ```
 type AndroidNotification struct {
        Title        string   `json:"title,omitempty"` // if specified, overrides the Title field of the Notification type
        Body         string   `json:"body,omitempty"`  // if specified, overrides the Body field of the Notification type
        Icon         string   `json:"icon,omitempty"`
        Color        string   `json:"color,omitempty"` // notification color in #RRGGBB format
        Sound        string   `json:"sound,omitempty"`
        Tag          string   `json:"tag,omitempty"`
        ClickAction  string   `json:"click_action,omitempty"`
        BodyLocKey   string   `json:"body_loc_key,omitempty"`
        BodyLocArgs  []string `json:"body_loc_args,omitempty"`
        TitleLocKey  string   `json:"title_loc_key,omitempty"`
        TitleLocArgs []string `json:"title_loc_args,omitempty"`
        ChannelID    string   `json:"channel_id,omitempty"`
        ImageURL     string   `json:"image,omitempty"`
    }
```

Is there any discrepancy in firebase documentation and struct or am I missing something?
Issue is, message are delivered to device but no sound or on screen display if device is sleeping. ( Happening on one plus 7 pro, only sometimes)

I checked the events using following commands 

       1.  Dial *#*#426#*#* to open the FCM Diagnostics page.
       2.  Tap the EVENTS button to show the event log.
       3.  Check whether the message was delivered to the device. There should be a log entry reading 

and saw that youtube message are coming with **HIGH** priority and priority of my messages is shown as **UNKNOWN**.

How I can send message with high priority as described in documentation?

**Comment by max202021** [comment]
Please let me now in case extra information is needed

**Comment by chemidy** [comment]
Hi, for now it's not supported by go SDK, there is an open Feature request #273

**Comment by max202021** [comment]
Thanks @chemidy , is there any timeline by when this feature will be available?

**Comment by chemidy** [comment]
I started working on it :)   hope to have some time this weekend to finish
