### ISSUE TITLE
Quation: EmailSignInLink API and generic dynamic link usage

### ISSUE THREAD

**Issue by bsr203** [firebase/firebase-admin-go#310]
This is a question about the API. Though I asked at SO, this is very specific to an API. Sorry for posting this as an issue, but should be a short response and I can proceed using this lib.

Please see the question at [SO](https://stackoverflow.com/q/59194241/303477)

Thank you

---

I am trying to use dynamic link feature (user to user share) as [here](https://firebase.google.com/docs/dynamic-links/use-cases/user-to-user) using go. The official sdk has one API similar to what I want. See [here](https://godoc.org/firebase.google.com/go/auth#Client.EmailSignInLink). But, Is that API only for SignIn or can it be used to make any dynamic link using firebase. Does firebase make any distinction about dynamic link whether it is for signin or other action. I see also a specific section for [email link ](https://firebase.google.com/docs/auth/admin/email-action-links#generate_email_link_for_sign-in)for signin in the doc and this API may be exclusively for that.

**Comment by bojeil-google** [comment]
`EmailSignInLink` API in Admin SDK is used for generating links for signing in users with Firebase Auth. The link should be embedded in an email sent to the user's underlying email.

This is not the same as the dynamic link feature (user to user share) you refer to.

Granted that the Firebase Auth feature can be used as a form of "invite" where one user invites another user to sign in to an app. However, some of the differences include:
1. The email link is sent via an email to the "invited" user's email (sent via a server and never shared client side, never with the original "inviter").
2. Applying the code in the link will generate Auth tokens and effectively sign in/ sign up the user to that app.

**Comment by bsr203** [comment]
Thank you so much for the explanation. It cleared up most of my doubts. Meanwhile I saw the generated client library for dynamic links with go. https://godoc.org/google.golang.org/api/firebasedynamiclinks/v1 I will explore further. thanks again
