### ISSUE TITLE
Example for global definition

### ISSUE THREAD

**Issue by beraybentesen** [firebase/firebase-admin-go#322]
Example for creating instance inside init method and accessing is required to prevent re-creating inside each package.

**Comment by hiranya911** [comment]
Each application has its own way of maintaining global state. That's more of a general Go programming question, and developers have their own preferences when it comes to matters like this. Personally, I like to define a type that encapsulates all the Firebase initialization and interaction logic, and then use an instance of that type in the rest of my app. For example:

Custom type with Firebase initialization logic: https://github.com/hiranya911/firecloud/blob/master/crypto-fire-alert/cryptocron/cryptocron.go
Usage in a web app: https://github.com/hiranya911/firecloud/blob/master/crypto-fire-alert/cryptocron/web/main.go

Beyond that we don't wish to provide any specific guidelines on how to organize and maintain state in various apps.
