### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by berk-can** [firebase/firebase-admin-go#330]
`
	opt := option.WithCredentialsFile("firebaseadmin.json")
	ctx := context.Background()
	app, err := firebase.NewApp(ctx, nil, opt)
	if err != nil {
		panic(fmt.Errorf("error initializing app: %v", err))
	}

	fcm,err:=app.Messaging(ctx)
	if err != nil {
		panic(err)
	}
	message := &messaging.Message{
		Data:  map[string]string{"test": "text"},
		Token: "I entered my Android device token here",
	}
	resp,err:=fcm.Send(ctx, message)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Response is: "+resp)
`

I have created Android app got token, tried token on web console test message works, then created golang project and provided same token there and sent message but doesnt work, response is:

> projects/winny-7c6c2/messages/0:1581370028248462%!b(MISSING)bdf7a92f9fd7ecd

**Comment by hiranya911** [comment]
If you're seeing the above response then the message was successfully handed off to FCM for delivery. Any problem is in the receiving end.

**Comment by berk-can** [comment]
@hiranya911 I am sorry for not providing all information, why do you think that problem is in receiving side, because I could successfully send test message via web console to same receiving device

**Comment by hiranya911** [comment]
Like I said, if you're seeing the above response (message ID string), then the message has been successfully handed off to FCM for delivery. The Admin SDK's role in sending FCM notifications ends there. Any issues with actual message delivery should be debugged from the FCM backend or client recipient end.

If you think the client app is implemented correctly, I'd recommend reaching out to Firebase support with the message ID string. They should be able to figure out why the message does not show up in the device.
