### ISSUE TITLE
TenantClient lacks custom tokens minting capabilities

### ISSUE THREAD

**Issue by darioielardi** [firebase/firebase-admin-go#337]
### Describe your environment

  * Operating System version:  macOS 10.15.3
  * Firebase SDK version: v3.12.0
  * Library version: ?
  * Firebase Product: auth

### Describe the problem

At the moment is not possible to mint tenant-aware custom tokens. The base auth client has a  CustomToken method, but there's no such function on the TenantClient.

Is this a work in progress or there's something I'm missing?

**Comment by hiranya911** [comment]
Yeah, it's not supported at the moment. Last I checked Auth team had a plan to support it. But we don't have a timeline to share just yet.

**Comment by hiranya911** [comment]
Turns out this can be supported now. See https://github.com/firebase/firebase-admin-node/pull/708

**Comment by xyzdevops** [comment]
I need this imminently and am happy to code the method into the go libraries. I will have a crack at it now.

**Comment by xyzdevops** [comment]
### API Changes





  








* At this time we cannot accept changes that affect the public API.  If you'd like to help 
    us make Firebase APIs better, please propose your change in an issue so that we 
    can discuss it together.

I fixed it but I guess I will have to wait for someone else to do so

**Comment by aren55555** [comment]
It looks the missing functions would approximately be:

```go
func (c *TenantClient) CustomToken(ctx context.Context, uid string) (string, error)
func (c *TenantClient) CustomTokenWithClaims(ctx context.Context, uid string, devClaims map[string]interface{}) (string, error)
```

These would closely match the receiver functions already defined on `*Client`

**Comment by hiranya911** [comment]
Just need to move the existing functions from `Client` to `baseClient` type so they become exposed on `TenantClient` as well.
