### ISSUE TITLE
FR: Support for Realtime Database

### ISSUE THREAD

**Issue by ellulpatrick** [firebase/firebase-admin-go#35]
Are there plans for this library to allow realtime access to the firebase realtime database?

Great work.

**Comment by hiranya911** [comment]
There's something in the works (see the `hkj-rtdb` branch).

**Comment by ellulpatrick** [comment]
May I ask if the intention is to use purely the REST API or if it will use a realtime connection as a proper client would?

**Comment by hiranya911** [comment]
Those are orthogonal issues. It is possible to implement realtime event listeners using the REST API (although it might not be as efficient). 

Current plan is to start off with a simple RTDB API based on REST support. If there's enough demand for it, we can implement realtime event listeners support incrementally. We would also welcome our open source community to help drive that effort by providing pull requests.

**Comment by hiranya911** [comment]
Implemented in #92
