### ISSUE TITLE
WithoutAuthentication client option seems to be ignored

### ISSUE THREAD

**Issue by mitar** [firebase/firebase-admin-go#357]
* Operating System version: Ubuntu 18.04.4
  * Firebase SDK version: (not sure what this is)
  * Library version: v3.12.0
  * Firebase Product: auth

#### Steps to reproduce:

I am trying to verify ID tokens. From me looking at the code it looks like that that does not need any API access (I am not checking for revocations), but I cannot really initialize the app like that.

#### Relevant Code:

```
	config := &firebase.Config{
		ProjectID: "foobar",
	}

	app, _ := firebase.NewApp(ctx, config, option.WithoutAuthentication())
        client, _ := app.Auth(ctx)
```

When I then call `client.VerifyIDToken(ctx, jwt)`, I get:

```
google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

I would expect that passing `WithoutAuthentication` would not try to obtain default credentials. It looks like `DialSettings.TokenSource` is used even if `DialSettings.NoAuth` is set?

**Comment by mitar** [comment]
My current workaround:

```
func (ts *DummyTokenSource) Token() (*oauth2.Token, error) {
	return nil, errors.New("This should never happen.")
}
```
```
	config := &firebase.Config{
		ProjectID: "foobar",
	}

	app, _ := firebase.NewApp(ctx, config, option.WithTokenSource(&DummyTokenSource{}))
	client, _ := app.Auth(ctx)
	_, err = client.VerifyIDToken(ctx, jwt)
```

**Comment by hiranya911** [comment]
Shouldn't happen unless you're using an old version of the SDK. Just tried the following which worked fine:

```
func TestMe(t *testing.T) {
	config := &firebase.Config{
		ProjectID: "foobar",
	}

	ctx := context.Background()
	app, err := firebase.NewApp(ctx, config, option.WithoutAuthentication())
	if err != nil {
		t.Fatal(err)
	}

	client, _ := app.Auth(ctx)
	if err != nil {
		t.Fatal(err)
	}

	_, err = client.VerifyIDToken(ctx, jwt)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by hiranya911** [comment]
New versions of the SDK defaults to `WithoutAuthentication` for public key fetch:

https://github.com/firebase/firebase-admin-go/blob/e088f55036154f0cccf661992f854abd8fb1333f/auth/token_verifier.go#L61-L75

**Comment by hiranya911** [comment]
Can you confirm whether the error is coming from `VerifyIDToken()` or some other initialization function? Perhaps `NewApp()`. That would make more sense.

**Comment by mitar** [comment]
Yes, it comes from `NewApp` already. I do not get to `VerifyIDToken`.

**Comment by hiranya911** [comment]
Ok, that's understandable. We have the following line of code:

https://github.com/firebase/firebase-admin-go/blob/e088f55036154f0cccf661992f854abd8fb1333f/firebase.go#L142-L148

Given we don't always need `creds` we can change the above to not fail. I'll try to work that into a future release.

**Comment by mitar** [comment]
Awesome!

**Comment by mitar** [comment]
Awesome, thanks!

**Comment by mitar** [comment]
When will this be part of a release?
