### ISSUE TITLE
go get firebase.google.com/go hangs

### ISSUE THREAD

**Issue by vedantroy** [firebase/firebase-admin-go#360]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Arch Linux

### [REQUIRED] Step 3: Describe the problem
Run `go get firebase.google.com/go`

I also tried doing `git clone --verbose go firebase.google.com/go`, and that failed to with "fatal: repository 'firebase.google.com/go' does not exist"

**Comment by hiranya911** [comment]
Did you wait long enough? It can take 1-2 minutes depending on your network and CPU resources, I just tried it, and worked fine for me:

```
$ mkdir gotemp
$ export GOPATH=~/Documents/gotemp/
$ go get firebase.google.com/go
$ ls gotemp/
pkg src
$ ls gotemp/src/
cloud.google.com    firebase.google.com github.com          go.opencensus.io    golang.org          google.golang.org
```

**Comment by vedantroy** [comment]
Doing `go get -d firebase.google.com/go` worked for me.
