### ISSUE TITLE
FR: Fix endpoint from v2beta1 to v2

### ISSUE THREAD

**Issue by sonatard** [firebase/firebase-admin-go#372]
* Firebase SDK version: master and v4 branch
  * Firebase Product: auth

https://github.com/firebase/firebase-admin-go/blob/4343fa831fed5b1bfeaa0d9824db99c78a5e261d/auth/tenant_mgt.go#L30

https://github.com/firebase/firebase-admin-go/blob/4343fa831fed5b1bfeaa0d9824db99c78a5e261d/auth/provider_config.go#L31

https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects.tenants/create

> https://identitytoolkit.googleapis.com/v2/

Please let me know if you have a reason to use beta.

**Comment by hiranya911** [comment]
I believe at the time v2 did not exist.

**Comment by hiranya911** [comment]
I'm going to close this as we don't see an immediate need to make this change. The upgrade will happen naturally in a future release, as we onboard new features into the Admin SDK.

**Comment by sonatard** [comment]
Fixed

https://github.com/firebase/firebase-admin-go/pull/412
