### ISSUE TITLE
RAW protobufs responses in SDK

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/firebase-admin-go#387]
Is there any way to access protobufs message from firestore. So I can get same structure as from Firestore triggers ? 

Ie. If you receive firestore trigger (onCreate for example) structure is dependent on firestore protobufs message:
https://cloud.google.com/firestore/docs/reference/rest/v1/Value

However if you access same document from firestore admin / client SDKs you will get documentSnapshot with data() function which returns classic json/map.

How to combine those two ? Is there any way to obtain RAW protobufs responses from SDKs ? Or only option is to use custom REST API client? Or keep two set of "models/structs" ?

**Comment by hiranya911** [comment]
Protos are not exposed in the public APIs: https://github.com/googleapis/google-cloud-go/blob/c8877ca3a97d95882aaef2fbffd949b484f0a8c2/firestore/document.go#L51

You can try filing a feature request at https://github.com/googleapis/google-cloud-go

**Comment by radvansky-tomas** [comment]
Yeah, was just reading same file 👍 , however is seems bit wrong to have different structure to came from same source Firestore Document...when in trigger it contains all those "StringValue etc..." while in DocumentSnapshot is "cleared"

**Comment by radvansky-tomas** [comment]
Its been already discussed here https://github.com/googleapis/google-cloud-go/issues/1438
