### ISSUE TITLE
FR: Add support for Device Groups messaging

### ISSUE THREAD

**Issue by speedwheel** [firebase/firebase-admin-go#394]
### [REQUIRED] Step 3: Describe the problem
At the moment if I want to group all my the registered devices per user, I can either use topics (which are insecure) or implement my own grouping system in the database. Both of these options are not the best, but actually there is a third option called `Device Groups` which is secure doesn't require managing all your tokens inside your database.

Unfortunately this feature is not supported inside the GO SDK at the moment, and I wanted to know if there is any hope in having this implemented in the near future.

**Comment by hiranya911** [comment]
Device groups is a feature of the legacy FCM API, and we have no plans to support it in the new SDK implementations. The FCM team has plans for some enhancements in topics that will likely address this use case in the future. I'll assign to @chong-shao who can confirm and close this issue.

**Comment by chong-shao** [comment]
what @hiranya911 said was correct.
