### ISSUE TITLE
Are error strings in any way localized?

### ISSUE THREAD

**Issue by skuskusku** [firebase/firebase-admin-go#401]
Hello everyone,

I am using firebase v4 to push notifications to android devices. When the Send method of the instance of messaging.Client fails, I only get a string error value and I wonder if this error string is localized. If not, I could compare it against e.g. "Requested entity was not found." to detect devices that have uninstalled my app. Is this string always plain english or does this depend on the locale the app is running under? Or does this error string come from the server, so I can never be sure if it stays the same?

What other options do I have to properly detect such an error, even if my golang binary runs on computer systems with any locale or language?  I am running my golang binary on windows.

Any help or insights appreciated,

-- 
Stefan

**Comment by hiranya911** [comment]
Error strings are not localized, but there's no guarantee that they will remain the same forever. Use the error handling functions provided in the SDK to check for specific error codes. See https://firebase.google.com/docs/reference/admin/error-handling
