### ISSUE TITLE
FR: trigger email verification process with firebase templates

### ISSUE THREAD

**Issue by SchiffFlieger** [firebase/firebase-admin-go#410]
As far as I can see, there is currently no way to trigger the email verification flow using the default firebase email templates. There is the method `EmailVerificationLinkWithSettings`, but this only returns the activation url to use it in custom emails. 

Are there any plans to include this feature? If so, I would be happy to support.

**Comment by hiranya911** [comment]
There are no immediate plans to provide this functionality as far as I know. I'd recommend filing a feature request via Firebase Support first.

**Comment by bojeil-google** [comment]
@hiranya911 is correct. We don't have an official way to do this in the Admin SDKs. I also recommend you file a [feature request](https://firebase.google.com/support) for this.

**Comment by guillermo-st** [comment]
Hi, I'm guessing there still no way to do this, right? I tried looking for the .SendVerificationEmail() method that is present in other languages's versions of the SDK, but it looks like Go's doesn't have it. 

How can I manually make an api call to firebase instead to trigger this flow? Or is it possible to obtain firebase's smpt host,port,user and password to use a go mail library instead?
