### ISSUE TITLE
FR: MFA support

### ISSUE THREAD

**Issue by jasperkuperus** [firebase/firebase-admin-go#421]
### Describe your environment

  * Operating System version: All
  * Firebase SDK version: v4.2.0
  * Firebase Product: auth

### Describe the problem

It would be nice if this library had support for MFA. Specifically, I'd like to get the enrolled second factors for a given user. For Node.js this is [available and documented](https://cloud.google.com/identity-platform/docs/admin/manage-mfa-users), but I don't see such a feature in this Go library. Are there any plans to add this?

**Comment by hiranya911** [comment]
No specific plans yet. But we are accepting PRs if somebody wishes to help speed things along.

**Comment by jasperkuperus** [comment]
Unfortunately, I don't have time to fully implement MFA. But I did just open a PR to add the MFA info to the user record. This already adds great value in my situation.

**Comment by hiranya911** [comment]
PR has been merged and updated to meet our API design requirements. This will be included in the next release.
