### ISSUE TITLE
cannot find module providing package google.golang.org/grpc/naming

### ISSUE THREAD

**Issue by musinit** [firebase/firebase-admin-go#426]
This is after go get firebase.google.com/go/v4 command

**Comment by qutubworldish** [comment]
Hi @musinit , I am facing the same issue with go get firebase.google.com/go/v4. 
Can you please tell me how you resolved this issue.

**Comment by 11Akhil** [comment]
same issue with me too, what i understand is that the firebase package is not getting stored on the desired locations where it is supposed to be maybe manually adding the firebase package under the gopath can solve the issue. if anyone else have some different way of fixing it please let me help out
