### ISSUE TITLE
Authentication emulator fails on clean environment to required default credentials

### ISSUE THREAD

**Issue by samlof** [firebase/firebase-admin-go#458]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: WSL Unix
  * Firebase SDK version: 4.6.0
  * Library version: v4.6.0
  * Firebase Product: auth emulator

### [REQUIRED] Step 3: Describe the problem

Running auth emulator with the wanted env variable FIREBASE_AUTH_EMULATOR_HOST fails.

#### Steps to reproduce:

Start a project in a clean machine. Add env variable FIREBASE_AUTH_EMULATOR_HOST and make firebase auth app.
It gives error `google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

#### Relevant Code:

```go
conf := &firebase.Config{ProjectID: "demo-project"}
app, err := firebase.NewApp(ctx, conf)
auth, err := app.Auth(ctx)
if err != nil {
   log.Fatalf("making firebase auth failed: %v", err) // this line is hit
}
```

The problem was missing the option `firebase.NewApp(ctx, conf, option.WithoutAuthentication())`. This isn't documented anywhere. Took me an hour of searching google and trying all kinds of things.

I came across this as Github Action failed to it. Tested on a brand new EC2 ubuntu instance in Amazon and fails too. With `WithoutAuthentication()` option both work as expected.

**Comment by samlof** [comment]
What you actually want is 
```go
authOpt := option.WithTokenSource(
			oauth2.StaticTokenSource(
				&oauth2.Token{
					AccessToken: "owner",
					TokenType:   "Bearer",
				}))
		app, err = firebase.NewApp(ctx, conf, authOpt)
```
This one works with creating users too. `WithoutAuthentication()` doesn't work with creating user

**Comment by MikolajMGT** [comment]
> What you actually want is
> 
> ```go
> authOpt := option.WithTokenSource(
> 			oauth2.StaticTokenSource(
> 				&oauth2.Token{
> 					AccessToken: "owner",
> 					TokenType:   "Bearer",
> 				}))
> app, err = firebase.NewApp(ctx, conf, authOpt)
> ```
> 
> This one works with creating users too. `WithoutAuthentication()` doesn't work with creating user

Hi @samlof, I've tried your solution with `&firebase.Config{ProjectID: "demo"}` but it throws 401 error error while creating new user:
`Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

Is it neccessary to add something else to config or options to run emulator properly?

**Comment by hiranya911** [comment]
Fixed with the above PR. Will be included in the next release.
