### ISSUE TITLE
FR: Start supporting ios 15's interruption-level

### ISSUE THREAD

**Issue by AntonNguyen** [firebase/firebase-admin-go#474]
### Describe your environment
- Operating System version: All
- Firebase SDK version: v4.7.0
- Firebase Product: FCM

### Describe the problem

With the release of iOS 15, they've added a new value to the payload:

- [`interruption-level`](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification)

> A string that indicates the importance and delivery timing of a notification. The string values “passive”, “active”, “time-sensitive”, or “critical” correspond to the UNNotificationInterruptionLevel enumeration cases.

The FCM library at the moment doesn't support this key.

**Comment by hiranya911** [comment]
You can always use the `CustomData` field to add parameters that are not explicitly defined on the type.

```
aps := &messaging.Aps{
  CustomData: map[string]interface{}{
    "interruption-level": "active",
  }
}
```

The SDK will serialize the json request correctly.

**Comment by AntonNguyen** [comment]
> You can always use the `CustomData` field to add parameters that are not explicitly defined on the type.
> 
> ```
> aps := &messaging.Aps{
>   CustomData: map[string]interface{}{
>     "interruption-level": "active",
>   }
> }
> ```
> 
> The SDK will serialize the json request correctly.

@hiranya911 You're right. That works. Thanks!
