### ISSUE TITLE
How to verify users emails?

### ISSUE THREAD

**Issue by marwan-nwh** [firebase/firebase-admin-go#487]
Hi,

I want to build a custom endpoint to verify users emails, but I can't find any function that could do that in the auth package.

Something like `auth.applyActionCode` [here](https://firebase.google.com/docs/auth/custom-email-handler#create_the_email_action_handler_page).  

Am I missing something?

**Comment by marwan-nwh** [comment]
@lahirumaramba Thanks for your help. No, I am already generating the email, but it links to a firebase endpoint, that verifies the email and gives you a success message. We want to build a custom page.

**Comment by lahirumaramba** [comment]
I see. I am not sure if that is currently supported in the REST API.

@prameshj is this something we currently support in GCIP?

**Comment by prameshj** [comment]
@marwan-nwh can you elaborate on your usecase - why is a custom page preferable here?

**Comment by marwan-nwh** [comment]
@prameshj We want to control where to redirect the users, the messages that show up, and we want to control the design of the page too.
Actually, we want to do that with all the actions like verifyEmail and resetPassword.

**Comment by prameshj** [comment]
cc @renkelvin

**Comment by prameshj** [comment]
the current SDK code invokes ‘/v1/accounts:sendOobCode’ API to firebase in reset password/verifyEmail flow and the firebase hosted UI ensures that the '/v1/accounts:signInWithEmailLink' is invoked.

In this issue, the ask is to send this request to a custom endpoint. This is not supported currently and I think is out of scope for the firebase SDKs.

> We want to control where to redirect the users, the messages that show up, and we want to control the design of the page too.
redirecting users can be done by setting the continue_uri as described in https://firebase.google.com/docs/auth/web/passing-state-in-email-actions#passing_statecontinue_url_in_email_actions

**Comment by marwan-nwh** [comment]
@prameshj  How is this out of the scope? Why does it exist in the JS SDK then? 
It is a normal request to customize that page. 
Anyway, I will try to use the API directly, or use the JS SDK. Thanks for your help.

For anyone searching in the future:
https://firebase.google.com/docs/auth/custom-email-handler#create_the_email_action_handler_page
https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#applyactioncode
https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithEmailLink
