### ISSUE TITLE
FR: get details according to a FCM token

### ISSUE THREAD

**Issue by sneko** [firebase/firebase-admin-go#488]
Hi,

I found there is a possibility from a FCM token to know some details about the platform (ios/android) and other properties.

I saw https://developers.google.com/instance-id/reference/server to do this, but it seems your Go SDK does not embed all endpoints. Is it something on your roadmap?

Thank you,

**Comment by chong-shao** [comment]
Hello, this feature request is similar to https://github.com/firebase/firebase-admin-node/issues/1179, please stay tuned for updates. 

Will close this one and keep https://github.com/firebase/firebase-admin-node/issues/1179 open
