### ISSUE TITLE
firebase-admin-go using hashicorp library which MPL licensed.

### ISSUE THREAD

**Issue by ravizbyte** [firebase/firebase-admin-go#516]
firebase-admin-go using hashicorp library which MPL licensed. Can we use some other MIT or apache licensed library.

**Comment by lahirumaramba** [comment]
Looks like the only hashicorp dependency in the dependency graph is `github.com/hashicorp/golang-lru` and it is not a direct module used by the admin-sdk. I think it is coming from `google.golang.org/api` module. Could you file an issue in that [repo](https://github.com/googleapis/google-api-go-client), please? That way the relevant teams should be able take a look. Thanks!
