### ISSUE TITLE
FR: CustomToken and VerifyIDToken Should Accept a Context

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-go#52]
These APIs currently do not accept a context, which is not correct. In our next major release (3.x), we should change these to accept a context like the other APIs in this package. This is unfortunately a breaking change, and hence cannot be released anytime soon.

**Comment by avishalom** [comment]
https://github.com/firebase/firebase-admin-go/pull/88

Breaking change - release at io

**Comment by matti777** [comment]
Will this change enable re-using the auth client (and its key source cache) on AppEngine? See my issue at https://stackoverflow.com/questions/47864216/making-the-auth-client-cacheable-on-appengine

**Comment by hiranya911** [comment]
This alone will not fix it. Our `auth.Client` also keeps a reference to an `http.Client`. In AppEngine, the `http.Client` implementation caches the context internally, which makes it unusable after the current request has ended. The `http.Client` instances are [meant to be reusable](https://golang.org/pkg/net/http/#Client), so the Admin SDK is right to do what it does.

I've discussed this with the AppEngine team, and they are reluctant to fix the existing URL Fetch transport since it is expected to go away in the future. An unrestricted http transport implementation is in the works which will be launched with the AppEngine Go 1.10 runtime. In the meantime we have a couple of options:

1. Live with this limitation in the AppEngine until Go 1.10 runtime is launched
2. Modify the Admin SDK, and separate the `http.Client` from `auth.httpKeySource`

Option 2 will require quite a bit of internal refactoring in addition to what's already proposed in this issue. So unless there's a really high demand for this, I'd prefer to not do it.

**Comment by matti777** [comment]
Yeah I've always found GAE's urlfetch client having a reference to the context slightly inconvenient.. ok then, I shall fork and implement the httpKeySource caching mechanism for my own purposes. Currently the auth is taking 250-300ms per request which is obviously not ok.

**Comment by matti777** [comment]
Well I got around creating a fugly hack for this; added *http.Client param to the related methods. For here https://github.com/matti777/firebase-admin-go, branch breaking_context_change.

Hope to see the urlfetch thing going away soon.

**Comment by hiranya911** [comment]
This was released in 3.0.0.
