### ISSUE TITLE
Maybe needed to update Installation in README.

### ISSUE THREAD

**Issue by kanonji** [firebase/firebase-admin-go#559]
### [REQUIRED] Step 3: Describe the problem

Instllation confuses me because it is different in the README and doc.
Perhaps the doc is correct, right?

#### In README

> ```
> go get firebase.google.com/go
> ```

#### In doc

https://firebase.google.com/docs/admin/setup#go

> ```
> # Install as a module dependency
> go get firebase.google.com/go/v4
> 
> # Install to $GOPATH
> go get firebase.google.com/go
> ```

**Comment by thatfiredev** [comment]
@kanonji Apologies for the confusion. You're right, the doc is correct. I have opened #562 to fix the README. 
Thanks for raising the issue :)

**Comment by thatfiredev** [comment]
Fixed :)

**Comment by kanonji** [comment]
I appreciate it.
