### ISSUE TITLE
FCM SendMessage rerurns 404

### ISSUE THREAD

**Issue by wubiner** [firebase/firebase-admin-go#664]
### [REQUIRED] Step 2: Describe your environment

  * Firebase SDK version: _____
https://pkg.go.dev/firebase.google.com/go  [v3.13.0+incompatible]

#### Steps to reproduce:

we use the go sdk for sending message,  the api SendMulticast returns err since yesterday.

"http error status: 404; reason: server responded with an unknown error; response: \<!DOCTYPE html\>"

**Comment by lahirumaramba** [comment]
`sendMulticast()` API has been deprecated since `v4.12.0` https://firebase.google.com/support/release-notes/admin/go#version_4120_-_12_july_2023

Please switch to `sendEachForMulticast()` instead.

**Comment by wubiner** [comment]
> `sendMulticast()` API has been deprecated since `v4.12.0` https://firebase.google.com/support/release-notes/admin/go#version_4120_-_12_july_2023 (The BE APIs has stopped working)
> 
> Please switch to `sendEachForMulticast()` instead.

so the https://pkg.go.dev/firebase.google.com/go will not update?
