### ISSUE TITLE
firebase.NewApp with credentials from memory instead of from file

### ISSUE THREAD

**Issue by ChrisBartonLC** [firebase/firebase-admin-go#72]
### Describe your environment

  * Operating System version: _____Docker
  * Firebase SDK version: _____Go HEAD of master branch
  * Library version: _____Go HEAD of master branch
  * Firebase Product: _____ (auth, database, storage, etc) auth

### Describe the problem

Is there a way to provide the credentials to "firebase.NewApp" as a byte array instead of a file via option.WithCredentialsFile? The reason I'm asking is because we store the file encrypted with KMS and would prefer not to write out the decrypted service account to a file and instead keep it in memory.

#### Steps to reproduce:

N/A

#### Relevant Code:

```
	opt := option.WithCredentialsFile("path/to/serviceAccountKey.json")
	client, err := firebase.NewApp(context.Background(), nil, opt)

```

**Comment by hiranya911** [comment]
Something along the lines of:

```
conf, err := google.JWTConfigFromJSON(jsonKeyBytes)
...
ts := conf.TokenSource(ctx)
firebase.NewApp(ctx, nil, option.WithTokenSource(ts))
```

https://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON

**Comment by ChrisBartonLC** [comment]
Thanks but when I use that method I get the error "project id not available". If I write the same byte array to a file and then use "option.WithCredentialsFile(...)" it works

    	// conf, err := google.JWTConfigFromJSON(secretFirebaseLcWebCsr)
	// if err != nil {
	// 	share_log.Logger.Fatal("Failed initializing firebase client credential", share_log.Logger.FmtError(err))
	// }
	// share_log.Logger.Info("Initialized firebase client credential")

	// firebaseClientLcWebCsr, err := firebase.NewApp(ctx, nil, option.WithTokenSource(conf.TokenSource(ctx)))

	firebaseClientLcWebCsr, err := firebase.NewApp(ctx, nil, option.WithCredentialsFile(secretFirebaseLcWebCsr))

**Comment by ChrisBartonLC** [comment]
Thanks but when I use that method I get the error "project id not available". If I write the same byte array to a file and then use "option.WithCredentialsFile(...)" it works

**Comment by hiranya911** [comment]
What is the function/line that triggers the error?

**Comment by ChrisBartonLC** [comment]
The error happens when I use the Auth client from the Firebase app so basically:

app := firebase.NewApp(ctx, nil, option.WithTokenSource(ts))
auth := app.Auth(ctx)
auth.VerifyIDToken(token)
-> { Invalid token: 'eyJh...samZQ': project id not available }

There is no problem is I go via a file. See attached file where "initFirebaseClientsCachingFile
[code.txt](https://github.com/firebase/firebase-admin-go/files/1636673/code.txt)
" works and "initFirebaseClients" doesn't

**Comment by ChrisBartonLC** [comment]
If I manually provide the Firebase project id I get this error:

firebase.NewApp(ctx, &firebase.Config{ProjectID: gcpProjectID}, opt)

 { Invalid token: 'eyJh...ZQ': Get https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_scope",
  "error_description" : "Empty or missing scope not allowed."
} }

**Comment by hiranya911** [comment]
`project_id` field gets lost when you take this route (along with a few others like `private_key`).  You can try passing it via `firebase.Config` instead. You might have to specify some OAuth2 scopes when calling `JWTConfigFromJSON()` to get past the other error.

Also might not be a bad idea to log a feature request against the https://godoc.org/google.golang.org/api/option package to provide a function that takes a `[]byte`.

**Comment by ChrisBartonLC** [comment]
Thanks I will. Seems JWTConfigFromJSON tries to decode to the struct below and the firebase service account has the following format so I can't see how the "project_id" got lost. I'll just use a tmp file until the Go SDK supports a byte array. Again thanks for your help

{"type":"service_account","client_email":"firebase-adminsdk-7tl4s@xx.iam.gserviceaccount.com","private_key_id":"84...40c15e","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEv...CisBulnI=\n-----END PRIVATE KEY-----\n","token_uri":"https://accounts.google.com/o/oauth2/token","project_id":"xx","client_secret":"","client_id":"1126...95","refresh_token":""} }

type credentialsFile struct {
	Type string `json:"type"` // serviceAccountKey or userCredentialsKey

	// Service Account fields
	ClientEmail  string `json:"client_email"`
	PrivateKeyID string `json:"private_key_id"`
	PrivateKey   string `json:"private_key"`
	TokenURL     string `json:"token_uri"`
	ProjectID    string `json:"project_id"`

	// User Credential fields
	// (These typically come from gcloud auth.)
	ClientSecret string `json:"client_secret"`
	ClientID     string `json:"client_id"`
	RefreshToken string `json:"refresh_token"`
}

**Comment by hiranya911** [comment]
The field gets parsed into the above struct, but what you pass into the Admin SDK is a `TokenSource`. That does not carry the project ID field.

**Comment by ChrisBartonLC** [comment]
OK it works if I hard code the project id and as you said provide the Firebase scopes e.g.

    conf, err := google.JWTConfigFromJSON(credentialBytes,
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/datastore",
		"https://www.googleapis.com/auth/devstorage.full_control",
		"https://www.googleapis.com/auth/firebase",
		"https://www.googleapis.com/auth/identitytoolkit",
		"https://www.googleapis.com/auth/userinfo.email")
    opt := option.WithTokenSource(conf.TokenSource(ctx))
    firebaseApp, err := firebase.NewApp(ctx, &firebase.Config{ProjectID: gcpProjectID}, opt)

**Comment by zxr90** [comment]
The new API works for me but couldnt find it anywhere from the docs. Should this be documented? will be happy to submit a PR.

**Comment by hiranya911** [comment]
Thanks @zxr90. I don't know where exactly to fit such a sample in https://firebase.google.com/docs/admin/setup. But feel free to put a small PR together. I like to see what you got in mind.
