### ISSUE TITLE
Please provide a byte array option for firebase.NewApp

### ISSUE THREAD

**Issue by ChrisBartonLC** [firebase/firebase-admin-go#73]
### Describe your environment

  * Operating System version: _____Docker
  * Firebase SDK version: _____Go HEAD of master branch
  * Library version: _____Go HEAD of master branch
  * Firebase Product: _____ (auth, database, storage, etc) auth

### Describe the problem

Please allow the credentials to be provided to "firebase.NewApp" as a byte array in addition to a file via the options. The reason I'm asking is because we store the file encrypted with KMS and would prefer not to write out the decrypted service account to a file and instead keep it in memory.

#### Steps to reproduce:

N/A

#### Relevant Code:

```
	opt := option.WithCredentialsFile("path/to/serviceAccountKey.json")
	client, err := firebase.NewApp(context.Background(), nil, opt)

```

**Comment by hiranya911** [comment]
@ChrisBartonLC this is not something we can fix in the Admin SDK. Please report against the Google API client: https://github.com/google/google-api-go-client

https://github.com/google/google-api-go-client/blob/master/option/option.go#L27
