### ISSUE TITLE
FR : list of topic subscriptions

### ISSUE THREAD

**Issue by chemidy** [firebase/firebase-admin-go#99]
We can now SubscribeToTopic and UnsubscribeFromTopic.

Is it possible to add a function ListTopicsForDevice based on "rel/topics" attribute  [from the Instance ID service](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances) ?

**Comment by hiranya911** [comment]
Sounds like a useful feature to me. @sampson-chen any thoughts?

**Comment by chemidy** [comment]
Any update ? Can I send a PR ?

**Comment by hiranya911** [comment]
@chemidy Before putting any time into writing code, can you propose what this API is going to look like (method/type signatures)? I can take that to the FCM team and get their thoughts on it.

**Comment by chong-shao** [comment]
Hi, we have plan to add this feature to the AdminSDK (along with a new HTTP API). But we don't have an estimated timeline now.
